services:
  mongodb:
    image: mongodb/mongodb-atlas-local:latest
    hostname: localhost
    ports:
      - "27017:27017"
    environment:
      MONGODB_LOAD_SAMPLE_DATA: "${ANTHROPIC_API_KEY:+true}"
