// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: mongocore/v1/ingestion.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileFormat int32

const (
	FileFormat_FILE_FORMAT_AUTO    FileFormat = 0
	FileFormat_FILE_FORMAT_CSV     FileFormat = 1
	FileFormat_FILE_FORMAT_JSON    FileFormat = 2
	FileFormat_FILE_FORMAT_NDJSON  FileFormat = 3
	FileFormat_FILE_FORMAT_PARQUET FileFormat = 4
)

// Enum value maps for FileFormat.
var (
	FileFormat_name = map[int32]string{
		0: "FILE_FORMAT_AUTO",
		1: "FILE_FORMAT_CSV",
		2: "FILE_FORMAT_JSON",
		3: "FILE_FORMAT_NDJSON",
		4: "FILE_FORMAT_PARQUET",
	}
	FileFormat_value = map[string]int32{
		"FILE_FORMAT_AUTO":    0,
		"FILE_FORMAT_CSV":     1,
		"FILE_FORMAT_JSON":    2,
		"FILE_FORMAT_NDJSON":  3,
		"FILE_FORMAT_PARQUET": 4,
	}
)

func (x FileFormat) Enum() *FileFormat {
	p := new(FileFormat)
	*p = x
	return p
}

func (x FileFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_mongocore_v1_ingestion_proto_enumTypes[0].Descriptor()
}

func (FileFormat) Type() protoreflect.EnumType {
	return &file_mongocore_v1_ingestion_proto_enumTypes[0]
}

func (x FileFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileFormat.Descriptor instead.
func (FileFormat) EnumDescriptor() ([]byte, []int) {
	return file_mongocore_v1_ingestion_proto_rawDescGZIP(), []int{0}
}

type ConflictStrategy int32

const (
	ConflictStrategy_CONFLICT_STRATEGY_SKIP      ConflictStrategy = 0
	ConflictStrategy_CONFLICT_STRATEGY_OVERWRITE ConflictStrategy = 1
	ConflictStrategy_CONFLICT_STRATEGY_MERGE     ConflictStrategy = 2
)

// Enum value maps for ConflictStrategy.
var (
	ConflictStrategy_name = map[int32]string{
		0: "CONFLICT_STRATEGY_SKIP",
		1: "CONFLICT_STRATEGY_OVERWRITE",
		2: "CONFLICT_STRATEGY_MERGE",
	}
	ConflictStrategy_value = map[string]int32{
		"CONFLICT_STRATEGY_SKIP":      0,
		"CONFLICT_STRATEGY_OVERWRITE": 1,
		"CONFLICT_STRATEGY_MERGE":     2,
	}
)

func (x ConflictStrategy) Enum() *ConflictStrategy {
	p := new(ConflictStrategy)
	*p = x
	return p
}

func (x ConflictStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConflictStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_mongocore_v1_ingestion_proto_enumTypes[1].Descriptor()
}

func (ConflictStrategy) Type() protoreflect.EnumType {
	return &file_mongocore_v1_ingestion_proto_enumTypes[1]
}

func (x ConflictStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConflictStrategy.Descriptor instead.
func (ConflictStrategy) EnumDescriptor() ([]byte, []int) {
	return file_mongocore_v1_ingestion_proto_rawDescGZIP(), []int{1}
}

type IngestJobStatus int32

const (
	IngestJobStatus_INGEST_JOB_STATUS_RUNNING   IngestJobStatus = 0
	IngestJobStatus_INGEST_JOB_STATUS_COMPLETED IngestJobStatus = 1
	IngestJobStatus_INGEST_JOB_STATUS_FAILED    IngestJobStatus = 2
	IngestJobStatus_INGEST_JOB_STATUS_CANCELLED IngestJobStatus = 3
)

// Enum value maps for IngestJobStatus.
var (
	IngestJobStatus_name = map[int32]string{
		0: "INGEST_JOB_STATUS_RUNNING",
		1: "INGEST_JOB_STATUS_COMPLETED",
		2: "INGEST_JOB_STATUS_FAILED",
		3: "INGEST_JOB_STATUS_CANCELLED",
	}
	IngestJobStatus_value = map[string]int32{
		"INGEST_JOB_STATUS_RUNNING":   0,
		"INGEST_JOB_STATUS_COMPLETED": 1,
		"INGEST_JOB_STATUS_FAILED":    2,
		"INGEST_JOB_STATUS_CANCELLED": 3,
	}
)

func (x IngestJobStatus) Enum() *IngestJobStatus {
	p := new(IngestJobStatus)
	*p = x
	return p
}

func (x IngestJobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IngestJobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_mongocore_v1_ingestion_proto_enumTypes[2].Descriptor()
}

func (IngestJobStatus) Type() protoreflect.EnumType {
	return &file_mongocore_v1_ingestion_proto_enumTypes[2]
}

func (x IngestJobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IngestJobStatus.Descriptor instead.
func (IngestJobStatus) EnumDescriptor() ([]byte, []int) {
	return file_mongocore_v1_ingestion_proto_rawDescGZIP(), []int{2}
}

type CsvOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delimiter     string                 `protobuf:"bytes,1,opt,name=delimiter,proto3" json:"delimiter,omitempty"`
	QuoteChar     string                 `protobuf:"bytes,2,opt,name=quote_char,json=quoteChar,proto3" json:"quote_char,omitempty"`
	HasHeader     bool                   `protobuf:"varint,3,opt,name=has_header,json=hasHeader,proto3" json:"has_header,omitempty"`
	CommentChar   string                 `protobuf:"bytes,4,opt,name=comment_char,json=commentChar,proto3" json:"comment_char,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CsvOptions) Reset() {
	*x = CsvOptions{}
	mi := &file_mongocore_v1_ingestion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CsvOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsvOptions) ProtoMessage() {}

func (x *CsvOptions) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_ingestion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsvOptions.ProtoReflect.Descriptor instead.
func (*CsvOptions) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_ingestion_proto_rawDescGZIP(), []int{0}
}

func (x *CsvOptions) GetDelimiter() string {
	if x != nil {
		return x.Delimiter
	}
	return ""
}

func (x *CsvOptions) GetQuoteChar() string {
	if x != nil {
		return x.QuoteChar
	}
	return ""
}

func (x *CsvOptions) GetHasHeader() bool {
	if x != nil {
		return x.HasHeader
	}
	return false
}

func (x *CsvOptions) GetCommentChar() string {
	if x != nil {
		return x.CommentChar
	}
	return ""
}

type IngestRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FilePath         string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Database         string                 `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	Collection       string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	Format           FileFormat             `protobuf:"varint,4,opt,name=format,proto3,enum=mongocore.v1.FileFormat" json:"format,omitempty"`
	DedupKey         []string               `protobuf:"bytes,5,rep,name=dedup_key,json=dedupKey,proto3" json:"dedup_key,omitempty"`
	ConflictStrategy ConflictStrategy       `protobuf:"varint,6,opt,name=conflict_strategy,json=conflictStrategy,proto3,enum=mongocore.v1.ConflictStrategy" json:"conflict_strategy,omitempty"`
	BatchSize        int32                  `protobuf:"varint,7,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	Concurrency      int32                  `protobuf:"varint,8,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	Expressions      []string               `protobuf:"bytes,9,rep,name=expressions,proto3" json:"expressions,omitempty"`
	SchemaOverrides  map[string]string      `protobuf:"bytes,10,rep,name=schema_overrides,json=schemaOverrides,proto3" json:"schema_overrides,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SampleSize       int32                  `protobuf:"varint,11,opt,name=sample_size,json=sampleSize,proto3" json:"sample_size,omitempty"`
	CsvOptions       *CsvOptions            `protobuf:"bytes,12,opt,name=csv_options,json=csvOptions,proto3" json:"csv_options,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_mongocore_v1_ingestion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_ingestion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_ingestion_proto_rawDescGZIP(), []int{1}
}

func (x *IngestRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *IngestRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *IngestRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *IngestRequest) GetFormat() FileFormat {
	if x != nil {
		return x.Format
	}
	return FileFormat_FILE_FORMAT_AUTO
}

func (x *IngestRequest) GetDedupKey() []string {
	if x != nil {
		return x.DedupKey
	}
	return nil
}

func (x *IngestRequest) GetConflictStrategy() ConflictStrategy {
	if x != nil {
		return x.ConflictStrategy
	}
	return ConflictStrategy_CONFLICT_STRATEGY_SKIP
}

func (x *IngestRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *IngestRequest) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *IngestRequest) GetExpressions() []string {
	if x != nil {
		return x.Expressions
	}
	return nil
}

func (x *IngestRequest) GetSchemaOverrides() map[string]string {
	if x != nil {
		return x.SchemaOverrides
	}
	return nil
}

func (x *IngestRequest) GetSampleSize() int32 {
	if x != nil {
		return x.SampleSize
	}
	return 0
}

func (x *IngestRequest) GetCsvOptions() *CsvOptions {
	if x != nil {
		return x.CsvOptions
	}
	return nil
}

type IngestResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status         IngestJobStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=mongocore.v1.IngestJobStatus" json:"status,omitempty"`
	InferredSchema map[string]string      `protobuf:"bytes,3,rep,name=inferred_schema,json=inferredSchema,proto3" json:"inferred_schema,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TotalRows      int64                  `protobuf:"varint,4,opt,name=total_rows,json=totalRows,proto3" json:"total_rows,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_mongocore_v1_ingestion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_ingestion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_ingestion_proto_rawDescGZIP(), []int{2}
}

func (x *IngestResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *IngestResponse) GetStatus() IngestJobStatus {
	if x != nil {
		return x.Status
	}
	return IngestJobStatus_INGEST_JOB_STATUS_RUNNING
}

func (x *IngestResponse) GetInferredSchema() map[string]string {
	if x != nil {
		return x.InferredSchema
	}
	return nil
}

func (x *IngestResponse) GetTotalRows() int64 {
	if x != nil {
		return x.TotalRows
	}
	return 0
}

type GetIngestStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIngestStatusRequest) Reset() {
	*x = GetIngestStatusRequest{}
	mi := &file_mongocore_v1_ingestion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIngestStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIngestStatusRequest) ProtoMessage() {}

func (x *GetIngestStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_ingestion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIngestStatusRequest.ProtoReflect.Descriptor instead.
func (*GetIngestStatusRequest) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_ingestion_proto_rawDescGZIP(), []int{3}
}

func (x *GetIngestStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetIngestStatusResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	JobId                string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status               IngestJobStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=mongocore.v1.IngestJobStatus" json:"status,omitempty"`
	TotalRows            int64                  `protobuf:"varint,3,opt,name=total_rows,json=totalRows,proto3" json:"total_rows,omitempty"`
	RowsProcessed        int64                  `protobuf:"varint,4,opt,name=rows_processed,json=rowsProcessed,proto3" json:"rows_processed,omitempty"`
	RowsInserted         int64                  `protobuf:"varint,5,opt,name=rows_inserted,json=rowsInserted,proto3" json:"rows_inserted,omitempty"`
	RowsSkipped          int64                  `protobuf:"varint,6,opt,name=rows_skipped,json=rowsSkipped,proto3" json:"rows_skipped,omitempty"`
	RowsFailed           int64                  `protobuf:"varint,7,opt,name=rows_failed,json=rowsFailed,proto3" json:"rows_failed,omitempty"`
	ElapsedMs            int64                  `protobuf:"varint,8,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	EstimatedRemainingMs int64                  `protobuf:"varint,9,opt,name=estimated_remaining_ms,json=estimatedRemainingMs,proto3" json:"estimated_remaining_ms,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetIngestStatusResponse) Reset() {
	*x = GetIngestStatusResponse{}
	mi := &file_mongocore_v1_ingestion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIngestStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIngestStatusResponse) ProtoMessage() {}

func (x *GetIngestStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_ingestion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIngestStatusResponse.ProtoReflect.Descriptor instead.
func (*GetIngestStatusResponse) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_ingestion_proto_rawDescGZIP(), []int{4}
}

func (x *GetIngestStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetIngestStatusResponse) GetStatus() IngestJobStatus {
	if x != nil {
		return x.Status
	}
	return IngestJobStatus_INGEST_JOB_STATUS_RUNNING
}

func (x *GetIngestStatusResponse) GetTotalRows() int64 {
	if x != nil {
		return x.TotalRows
	}
	return 0
}

func (x *GetIngestStatusResponse) GetRowsProcessed() int64 {
	if x != nil {
		return x.RowsProcessed
	}
	return 0
}

func (x *GetIngestStatusResponse) GetRowsInserted() int64 {
	if x != nil {
		return x.RowsInserted
	}
	return 0
}

func (x *GetIngestStatusResponse) GetRowsSkipped() int64 {
	if x != nil {
		return x.RowsSkipped
	}
	return 0
}

func (x *GetIngestStatusResponse) GetRowsFailed() int64 {
	if x != nil {
		return x.RowsFailed
	}
	return 0
}

func (x *GetIngestStatusResponse) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

func (x *GetIngestStatusResponse) GetEstimatedRemainingMs() int64 {
	if x != nil {
		return x.EstimatedRemainingMs
	}
	return 0
}

type ListIngestJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIngestJobsRequest) Reset() {
	*x = ListIngestJobsRequest{}
	mi := &file_mongocore_v1_ingestion_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIngestJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIngestJobsRequest) ProtoMessage() {}

func (x *ListIngestJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_ingestion_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIngestJobsRequest.ProtoReflect.Descriptor instead.
func (*ListIngestJobsRequest) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_ingestion_proto_rawDescGZIP(), []int{5}
}

type ListIngestJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*IngestJobSummary    `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIngestJobsResponse) Reset() {
	*x = ListIngestJobsResponse{}
	mi := &file_mongocore_v1_ingestion_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIngestJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIngestJobsResponse) ProtoMessage() {}

func (x *ListIngestJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_ingestion_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIngestJobsResponse.ProtoReflect.Descriptor instead.
func (*ListIngestJobsResponse) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_ingestion_proto_rawDescGZIP(), []int{6}
}

func (x *ListIngestJobsResponse) GetJobs() []*IngestJobSummary {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type IngestJobSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Database      string                 `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,4,opt,name=collection,proto3" json:"collection,omitempty"`
	Status        IngestJobStatus        `protobuf:"varint,5,opt,name=status,proto3,enum=mongocore.v1.IngestJobStatus" json:"status,omitempty"`
	TotalRows     int64                  `protobuf:"varint,6,opt,name=total_rows,json=totalRows,proto3" json:"total_rows,omitempty"`
	RowsProcessed int64                  `protobuf:"varint,7,opt,name=rows_processed,json=rowsProcessed,proto3" json:"rows_processed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestJobSummary) Reset() {
	*x = IngestJobSummary{}
	mi := &file_mongocore_v1_ingestion_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestJobSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestJobSummary) ProtoMessage() {}

func (x *IngestJobSummary) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_ingestion_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestJobSummary.ProtoReflect.Descriptor instead.
func (*IngestJobSummary) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_ingestion_proto_rawDescGZIP(), []int{7}
}

func (x *IngestJobSummary) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *IngestJobSummary) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *IngestJobSummary) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *IngestJobSummary) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *IngestJobSummary) GetStatus() IngestJobStatus {
	if x != nil {
		return x.Status
	}
	return IngestJobStatus_INGEST_JOB_STATUS_RUNNING
}

func (x *IngestJobSummary) GetTotalRows() int64 {
	if x != nil {
		return x.TotalRows
	}
	return 0
}

func (x *IngestJobSummary) GetRowsProcessed() int64 {
	if x != nil {
		return x.RowsProcessed
	}
	return 0
}

type CancelIngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelIngestRequest) Reset() {
	*x = CancelIngestRequest{}
	mi := &file_mongocore_v1_ingestion_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelIngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelIngestRequest) ProtoMessage() {}

func (x *CancelIngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_ingestion_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelIngestRequest.ProtoReflect.Descriptor instead.
func (*CancelIngestRequest) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_ingestion_proto_rawDescGZIP(), []int{8}
}

func (x *CancelIngestRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelIngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelIngestResponse) Reset() {
	*x = CancelIngestResponse{}
	mi := &file_mongocore_v1_ingestion_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelIngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelIngestResponse) ProtoMessage() {}

func (x *CancelIngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_ingestion_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelIngestResponse.ProtoReflect.Descriptor instead.
func (*CancelIngestResponse) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_ingestion_proto_rawDescGZIP(), []int{9}
}

func (x *CancelIngestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type WatchDirectoryRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Path             string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	FilePattern      string                 `protobuf:"bytes,2,opt,name=file_pattern,json=filePattern,proto3" json:"file_pattern,omitempty"`
	Database         string                 `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	Collection       string                 `protobuf:"bytes,4,opt,name=collection,proto3" json:"collection,omitempty"`
	ConflictStrategy ConflictStrategy       `protobuf:"varint,5,opt,name=conflict_strategy,json=conflictStrategy,proto3,enum=mongocore.v1.ConflictStrategy" json:"conflict_strategy,omitempty"`
	DedupKey         []string               `protobuf:"bytes,6,rep,name=dedup_key,json=dedupKey,proto3" json:"dedup_key,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WatchDirectoryRequest) Reset() {
	*x = WatchDirectoryRequest{}
	mi := &file_mongocore_v1_ingestion_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchDirectoryRequest) ProtoMessage() {}

func (x *WatchDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_ingestion_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchDirectoryRequest.ProtoReflect.Descriptor instead.
func (*WatchDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_ingestion_proto_rawDescGZIP(), []int{10}
}

func (x *WatchDirectoryRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WatchDirectoryRequest) GetFilePattern() string {
	if x != nil {
		return x.FilePattern
	}
	return ""
}

func (x *WatchDirectoryRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *WatchDirectoryRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *WatchDirectoryRequest) GetConflictStrategy() ConflictStrategy {
	if x != nil {
		return x.ConflictStrategy
	}
	return ConflictStrategy_CONFLICT_STRATEGY_SKIP
}

func (x *WatchDirectoryRequest) GetDedupKey() []string {
	if x != nil {
		return x.DedupKey
	}
	return nil
}

type WatchDirectoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WatchId       string                 `protobuf:"bytes,1,opt,name=watch_id,json=watchId,proto3" json:"watch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchDirectoryResponse) Reset() {
	*x = WatchDirectoryResponse{}
	mi := &file_mongocore_v1_ingestion_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchDirectoryResponse) ProtoMessage() {}

func (x *WatchDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_ingestion_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchDirectoryResponse.ProtoReflect.Descriptor instead.
func (*WatchDirectoryResponse) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_ingestion_proto_rawDescGZIP(), []int{11}
}

func (x *WatchDirectoryResponse) GetWatchId() string {
	if x != nil {
		return x.WatchId
	}
	return ""
}

type StopWatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WatchId       string                 `protobuf:"bytes,1,opt,name=watch_id,json=watchId,proto3" json:"watch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopWatchRequest) Reset() {
	*x = StopWatchRequest{}
	mi := &file_mongocore_v1_ingestion_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopWatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopWatchRequest) ProtoMessage() {}

func (x *StopWatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_ingestion_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopWatchRequest.ProtoReflect.Descriptor instead.
func (*StopWatchRequest) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_ingestion_proto_rawDescGZIP(), []int{12}
}

func (x *StopWatchRequest) GetWatchId() string {
	if x != nil {
		return x.WatchId
	}
	return ""
}

type StopWatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopWatchResponse) Reset() {
	*x = StopWatchResponse{}
	mi := &file_mongocore_v1_ingestion_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopWatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopWatchResponse) ProtoMessage() {}

func (x *StopWatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_ingestion_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopWatchResponse.ProtoReflect.Descriptor instead.
func (*StopWatchResponse) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_ingestion_proto_rawDescGZIP(), []int{13}
}

func (x *StopWatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_mongocore_v1_ingestion_proto protoreflect.FileDescriptor

const file_mongocore_v1_ingestion_proto_rawDesc = "" +
	"\n" +
	"\x1cmongocore/v1/ingestion.proto\x12\fmongocore.v1\"\x8b\x01\n" +
	"\n" +
	"CsvOptions\x12\x1c\n" +
	"\tdelimiter\x18\x01 \x01(\tR\tdelimiter\x12\x1d\n" +
	"\n" +
	"quote_char\x18\x02 \x01(\tR\tquoteChar\x12\x1d\n" +
	"\n" +
	"has_header\x18\x03 \x01(\bR\thasHeader\x12!\n" +
	"\fcomment_char\x18\x04 \x01(\tR\vcommentChar\"\xe4\x04\n" +
	"\rIngestRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x120\n" +
	"\x06format\x18\x04 \x01(\x0e2\x18.mongocore.v1.FileFormatR\x06format\x12\x1b\n" +
	"\tdedup_key\x18\x05 \x03(\tR\bdedupKey\x12K\n" +
	"\x11conflict_strategy\x18\x06 \x01(\x0e2\x1e.mongocore.v1.ConflictStrategyR\x10conflictStrategy\x12\x1d\n" +
	"\n" +
	"batch_size\x18\a \x01(\x05R\tbatchSize\x12 \n" +
	"\vconcurrency\x18\b \x01(\x05R\vconcurrency\x12 \n" +
	"\vexpressions\x18\t \x03(\tR\vexpressions\x12[\n" +
	"\x10schema_overrides\x18\n" +
	" \x03(\v20.mongocore.v1.IngestRequest.SchemaOverridesEntryR\x0fschemaOverrides\x12\x1f\n" +
	"\vsample_size\x18\v \x01(\x05R\n" +
	"sampleSize\x129\n" +
	"\vcsv_options\x18\f \x01(\v2\x18.mongocore.v1.CsvOptionsR\n" +
	"csvOptions\x1aB\n" +
	"\x14SchemaOverridesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9b\x02\n" +
	"\x0eIngestResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.mongocore.v1.IngestJobStatusR\x06status\x12Y\n" +
	"\x0finferred_schema\x18\x03 \x03(\v20.mongocore.v1.IngestResponse.InferredSchemaEntryR\x0einferredSchema\x12\x1d\n" +
	"\n" +
	"total_rows\x18\x04 \x01(\x03R\ttotalRows\x1aA\n" +
	"\x13InferredSchemaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\x16GetIngestStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xeb\x02\n" +
	"\x17GetIngestStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.mongocore.v1.IngestJobStatusR\x06status\x12\x1d\n" +
	"\n" +
	"total_rows\x18\x03 \x01(\x03R\ttotalRows\x12%\n" +
	"\x0erows_processed\x18\x04 \x01(\x03R\rrowsProcessed\x12#\n" +
	"\rrows_inserted\x18\x05 \x01(\x03R\frowsInserted\x12!\n" +
	"\frows_skipped\x18\x06 \x01(\x03R\vrowsSkipped\x12\x1f\n" +
	"\vrows_failed\x18\a \x01(\x03R\n" +
	"rowsFailed\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\b \x01(\x03R\telapsedMs\x124\n" +
	"\x16estimated_remaining_ms\x18\t \x01(\x03R\x14estimatedRemainingMs\"\x17\n" +
	"\x15ListIngestJobsRequest\"L\n" +
	"\x16ListIngestJobsResponse\x122\n" +
	"\x04jobs\x18\x01 \x03(\v2\x1e.mongocore.v1.IngestJobSummaryR\x04jobs\"\xff\x01\n" +
	"\x10IngestJobSummary\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x1a\n" +
	"\bdatabase\x18\x03 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x04 \x01(\tR\n" +
	"collection\x125\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1d.mongocore.v1.IngestJobStatusR\x06status\x12\x1d\n" +
	"\n" +
	"total_rows\x18\x06 \x01(\x03R\ttotalRows\x12%\n" +
	"\x0erows_processed\x18\a \x01(\x03R\rrowsProcessed\",\n" +
	"\x13CancelIngestRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"0\n" +
	"\x14CancelIngestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xf4\x01\n" +
	"\x15WatchDirectoryRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12!\n" +
	"\ffile_pattern\x18\x02 \x01(\tR\vfilePattern\x12\x1a\n" +
	"\bdatabase\x18\x03 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x04 \x01(\tR\n" +
	"collection\x12K\n" +
	"\x11conflict_strategy\x18\x05 \x01(\x0e2\x1e.mongocore.v1.ConflictStrategyR\x10conflictStrategy\x12\x1b\n" +
	"\tdedup_key\x18\x06 \x03(\tR\bdedupKey\"3\n" +
	"\x16WatchDirectoryResponse\x12\x19\n" +
	"\bwatch_id\x18\x01 \x01(\tR\awatchId\"-\n" +
	"\x10StopWatchRequest\x12\x19\n" +
	"\bwatch_id\x18\x01 \x01(\tR\awatchId\"-\n" +
	"\x11StopWatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*~\n" +
	"\n" +
	"FileFormat\x12\x14\n" +
	"\x10FILE_FORMAT_AUTO\x10\x00\x12\x13\n" +
	"\x0fFILE_FORMAT_CSV\x10\x01\x12\x14\n" +
	"\x10FILE_FORMAT_JSON\x10\x02\x12\x16\n" +
	"\x12FILE_FORMAT_NDJSON\x10\x03\x12\x17\n" +
	"\x13FILE_FORMAT_PARQUET\x10\x04*l\n" +
	"\x10ConflictStrategy\x12\x1a\n" +
	"\x16CONFLICT_STRATEGY_SKIP\x10\x00\x12\x1f\n" +
	"\x1bCONFLICT_STRATEGY_OVERWRITE\x10\x01\x12\x1b\n" +
	"\x17CONFLICT_STRATEGY_MERGE\x10\x02*\x90\x01\n" +
	"\x0fIngestJobStatus\x12\x1d\n" +
	"\x19INGEST_JOB_STATUS_RUNNING\x10\x00\x12\x1f\n" +
	"\x1bINGEST_JOB_STATUS_COMPLETED\x10\x01\x12\x1c\n" +
	"\x18INGEST_JOB_STATUS_FAILED\x10\x02\x12\x1f\n" +
	"\x1bINGEST_JOB_STATUS_CANCELLED\x10\x03B-Z+github.com/rozza/mongocore/clients/go/protob\x06proto3"

var (
	file_mongocore_v1_ingestion_proto_rawDescOnce sync.Once
	file_mongocore_v1_ingestion_proto_rawDescData []byte
)

func file_mongocore_v1_ingestion_proto_rawDescGZIP() []byte {
	file_mongocore_v1_ingestion_proto_rawDescOnce.Do(func() {
		file_mongocore_v1_ingestion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mongocore_v1_ingestion_proto_rawDesc), len(file_mongocore_v1_ingestion_proto_rawDesc)))
	})
	return file_mongocore_v1_ingestion_proto_rawDescData
}

var file_mongocore_v1_ingestion_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_mongocore_v1_ingestion_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_mongocore_v1_ingestion_proto_goTypes = []any{
	(FileFormat)(0),                 // 0: mongocore.v1.FileFormat
	(ConflictStrategy)(0),           // 1: mongocore.v1.ConflictStrategy
	(IngestJobStatus)(0),            // 2: mongocore.v1.IngestJobStatus
	(*CsvOptions)(nil),              // 3: mongocore.v1.CsvOptions
	(*IngestRequest)(nil),           // 4: mongocore.v1.IngestRequest
	(*IngestResponse)(nil),          // 5: mongocore.v1.IngestResponse
	(*GetIngestStatusRequest)(nil),  // 6: mongocore.v1.GetIngestStatusRequest
	(*GetIngestStatusResponse)(nil), // 7: mongocore.v1.GetIngestStatusResponse
	(*ListIngestJobsRequest)(nil),   // 8: mongocore.v1.ListIngestJobsRequest
	(*ListIngestJobsResponse)(nil),  // 9: mongocore.v1.ListIngestJobsResponse
	(*IngestJobSummary)(nil),        // 10: mongocore.v1.IngestJobSummary
	(*CancelIngestRequest)(nil),     // 11: mongocore.v1.CancelIngestRequest
	(*CancelIngestResponse)(nil),    // 12: mongocore.v1.CancelIngestResponse
	(*WatchDirectoryRequest)(nil),   // 13: mongocore.v1.WatchDirectoryRequest
	(*WatchDirectoryResponse)(nil),  // 14: mongocore.v1.WatchDirectoryResponse
	(*StopWatchRequest)(nil),        // 15: mongocore.v1.StopWatchRequest
	(*StopWatchResponse)(nil),       // 16: mongocore.v1.StopWatchResponse
	nil,                             // 17: mongocore.v1.IngestRequest.SchemaOverridesEntry
	nil,                             // 18: mongocore.v1.IngestResponse.InferredSchemaEntry
}
var file_mongocore_v1_ingestion_proto_depIdxs = []int32{
	0,  // 0: mongocore.v1.IngestRequest.format:type_name -> mongocore.v1.FileFormat
	1,  // 1: mongocore.v1.IngestRequest.conflict_strategy:type_name -> mongocore.v1.ConflictStrategy
	17, // 2: mongocore.v1.IngestRequest.schema_overrides:type_name -> mongocore.v1.IngestRequest.SchemaOverridesEntry
	3,  // 3: mongocore.v1.IngestRequest.csv_options:type_name -> mongocore.v1.CsvOptions
	2,  // 4: mongocore.v1.IngestResponse.status:type_name -> mongocore.v1.IngestJobStatus
	18, // 5: mongocore.v1.IngestResponse.inferred_schema:type_name -> mongocore.v1.IngestResponse.InferredSchemaEntry
	2,  // 6: mongocore.v1.GetIngestStatusResponse.status:type_name -> mongocore.v1.IngestJobStatus
	10, // 7: mongocore.v1.ListIngestJobsResponse.jobs:type_name -> mongocore.v1.IngestJobSummary
	2,  // 8: mongocore.v1.IngestJobSummary.status:type_name -> mongocore.v1.IngestJobStatus
	1,  // 9: mongocore.v1.WatchDirectoryRequest.conflict_strategy:type_name -> mongocore.v1.ConflictStrategy
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_mongocore_v1_ingestion_proto_init() }
func file_mongocore_v1_ingestion_proto_init() {
	if File_mongocore_v1_ingestion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mongocore_v1_ingestion_proto_rawDesc), len(file_mongocore_v1_ingestion_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mongocore_v1_ingestion_proto_goTypes,
		DependencyIndexes: file_mongocore_v1_ingestion_proto_depIdxs,
		EnumInfos:         file_mongocore_v1_ingestion_proto_enumTypes,
		MessageInfos:      file_mongocore_v1_ingestion_proto_msgTypes,
	}.Build()
	File_mongocore_v1_ingestion_proto = out.File
	file_mongocore_v1_ingestion_proto_goTypes = nil
	file_mongocore_v1_ingestion_proto_depIdxs = nil
}
