// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mongocore/v1/ingestion.proto

package proto

// FileFormat enumerates supported file formats for ingestion.
type FileFormat int32

const (
	FileFormat_FILE_FORMAT_AUTO    FileFormat = 0
	FileFormat_FILE_FORMAT_CSV     FileFormat = 1
	FileFormat_FILE_FORMAT_JSON    FileFormat = 2
	FileFormat_FILE_FORMAT_NDJSON  FileFormat = 3
	FileFormat_FILE_FORMAT_PARQUET FileFormat = 4
)

// ConflictStrategy enumerates strategies for handling duplicate keys during ingestion.
type ConflictStrategy int32

const (
	ConflictStrategy_CONFLICT_STRATEGY_SKIP      ConflictStrategy = 0
	ConflictStrategy_CONFLICT_STRATEGY_OVERWRITE ConflictStrategy = 1
	ConflictStrategy_CONFLICT_STRATEGY_MERGE     ConflictStrategy = 2
)

// IngestJobStatus enumerates the possible states of an ingestion job.
type IngestJobStatus int32

const (
	IngestJobStatus_INGEST_JOB_STATUS_RUNNING   IngestJobStatus = 0
	IngestJobStatus_INGEST_JOB_STATUS_COMPLETED IngestJobStatus = 1
	IngestJobStatus_INGEST_JOB_STATUS_FAILED    IngestJobStatus = 2
	IngestJobStatus_INGEST_JOB_STATUS_CANCELLED IngestJobStatus = 3
)

// CsvOptions configures CSV parsing behavior.
type CsvOptions struct {
	Delimiter   string `protobuf:"bytes,1,opt,name=delimiter,proto3" json:"delimiter,omitempty"`
	QuoteChar   string `protobuf:"bytes,2,opt,name=quote_char,json=quoteChar,proto3" json:"quote_char,omitempty"`
	HasHeader   bool   `protobuf:"varint,3,opt,name=has_header,json=hasHeader,proto3" json:"has_header,omitempty"`
	CommentChar string `protobuf:"bytes,4,opt,name=comment_char,json=commentChar,proto3" json:"comment_char,omitempty"`
}

func (x *CsvOptions) GetDelimiter() string {
	if x != nil {
		return x.Delimiter
	}
	return ""
}

func (x *CsvOptions) GetQuoteChar() string {
	if x != nil {
		return x.QuoteChar
	}
	return ""
}

func (x *CsvOptions) GetHasHeader() bool {
	if x != nil {
		return x.HasHeader
	}
	return false
}

func (x *CsvOptions) GetCommentChar() string {
	if x != nil {
		return x.CommentChar
	}
	return ""
}

// IngestRequest starts an ingestion job.
type IngestRequest struct {
	FilePath         string            `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Database         string            `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	Collection       string            `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	Format           FileFormat        `protobuf:"varint,4,opt,name=format,proto3,enum=mongocore.v1.FileFormat" json:"format,omitempty"`
	DedupKey         []string          `protobuf:"bytes,5,rep,name=dedup_key,json=dedupKey,proto3" json:"dedup_key,omitempty"`
	ConflictStrategy ConflictStrategy  `protobuf:"varint,6,opt,name=conflict_strategy,json=conflictStrategy,proto3,enum=mongocore.v1.ConflictStrategy" json:"conflict_strategy,omitempty"`
	BatchSize        int32             `protobuf:"varint,7,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	Concurrency      int32             `protobuf:"varint,8,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	Expressions      []string          `protobuf:"bytes,9,rep,name=expressions,proto3" json:"expressions,omitempty"`
	SchemaOverrides  map[string]string `protobuf:"bytes,10,rep,name=schema_overrides,json=schemaOverrides,proto3" json:"schema_overrides,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SampleSize       int32             `protobuf:"varint,11,opt,name=sample_size,json=sampleSize,proto3" json:"sample_size,omitempty"`
	CsvOptions       *CsvOptions       `protobuf:"bytes,12,opt,name=csv_options,json=csvOptions,proto3" json:"csv_options,omitempty"`
}

func (x *IngestRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *IngestRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *IngestRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *IngestRequest) GetFormat() FileFormat {
	if x != nil {
		return x.Format
	}
	return FileFormat_FILE_FORMAT_AUTO
}

func (x *IngestRequest) GetDedupKey() []string {
	if x != nil {
		return x.DedupKey
	}
	return nil
}

func (x *IngestRequest) GetConflictStrategy() ConflictStrategy {
	if x != nil {
		return x.ConflictStrategy
	}
	return ConflictStrategy_CONFLICT_STRATEGY_SKIP
}

func (x *IngestRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *IngestRequest) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *IngestRequest) GetExpressions() []string {
	if x != nil {
		return x.Expressions
	}
	return nil
}

func (x *IngestRequest) GetSchemaOverrides() map[string]string {
	if x != nil {
		return x.SchemaOverrides
	}
	return nil
}

func (x *IngestRequest) GetSampleSize() int32 {
	if x != nil {
		return x.SampleSize
	}
	return 0
}

func (x *IngestRequest) GetCsvOptions() *CsvOptions {
	if x != nil {
		return x.CsvOptions
	}
	return nil
}

// IngestResponse is returned when an ingestion job is started.
type IngestResponse struct {
	JobId          string            `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status         IngestJobStatus   `protobuf:"varint,2,opt,name=status,proto3,enum=mongocore.v1.IngestJobStatus" json:"status,omitempty"`
	InferredSchema map[string]string `protobuf:"bytes,3,rep,name=inferred_schema,json=inferredSchema,proto3" json:"inferred_schema,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TotalRows      int64             `protobuf:"varint,4,opt,name=total_rows,json=totalRows,proto3" json:"total_rows,omitempty"`
}

func (x *IngestResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *IngestResponse) GetStatus() IngestJobStatus {
	if x != nil {
		return x.Status
	}
	return IngestJobStatus_INGEST_JOB_STATUS_RUNNING
}

func (x *IngestResponse) GetInferredSchema() map[string]string {
	if x != nil {
		return x.InferredSchema
	}
	return nil
}

func (x *IngestResponse) GetTotalRows() int64 {
	if x != nil {
		return x.TotalRows
	}
	return 0
}

// GetIngestStatusRequest queries the status of an ingestion job.
type GetIngestStatusRequest struct {
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
}

func (x *GetIngestStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// GetIngestStatusResponse contains detailed ingestion job status.
type GetIngestStatusResponse struct {
	JobId                string          `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status               IngestJobStatus `protobuf:"varint,2,opt,name=status,proto3,enum=mongocore.v1.IngestJobStatus" json:"status,omitempty"`
	TotalRows            int64           `protobuf:"varint,3,opt,name=total_rows,json=totalRows,proto3" json:"total_rows,omitempty"`
	RowsProcessed        int64           `protobuf:"varint,4,opt,name=rows_processed,json=rowsProcessed,proto3" json:"rows_processed,omitempty"`
	RowsInserted         int64           `protobuf:"varint,5,opt,name=rows_inserted,json=rowsInserted,proto3" json:"rows_inserted,omitempty"`
	RowsSkipped          int64           `protobuf:"varint,6,opt,name=rows_skipped,json=rowsSkipped,proto3" json:"rows_skipped,omitempty"`
	RowsFailed           int64           `protobuf:"varint,7,opt,name=rows_failed,json=rowsFailed,proto3" json:"rows_failed,omitempty"`
	ElapsedMs            int64           `protobuf:"varint,8,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	EstimatedRemainingMs int64           `protobuf:"varint,9,opt,name=estimated_remaining_ms,json=estimatedRemainingMs,proto3" json:"estimated_remaining_ms,omitempty"`
}

func (x *GetIngestStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetIngestStatusResponse) GetStatus() IngestJobStatus {
	if x != nil {
		return x.Status
	}
	return IngestJobStatus_INGEST_JOB_STATUS_RUNNING
}

func (x *GetIngestStatusResponse) GetTotalRows() int64 {
	if x != nil {
		return x.TotalRows
	}
	return 0
}

func (x *GetIngestStatusResponse) GetRowsProcessed() int64 {
	if x != nil {
		return x.RowsProcessed
	}
	return 0
}

func (x *GetIngestStatusResponse) GetRowsInserted() int64 {
	if x != nil {
		return x.RowsInserted
	}
	return 0
}

func (x *GetIngestStatusResponse) GetRowsSkipped() int64 {
	if x != nil {
		return x.RowsSkipped
	}
	return 0
}

func (x *GetIngestStatusResponse) GetRowsFailed() int64 {
	if x != nil {
		return x.RowsFailed
	}
	return 0
}

func (x *GetIngestStatusResponse) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

func (x *GetIngestStatusResponse) GetEstimatedRemainingMs() int64 {
	if x != nil {
		return x.EstimatedRemainingMs
	}
	return 0
}

// ListIngestJobsRequest lists all ingestion jobs.
type ListIngestJobsRequest struct{}

// ListIngestJobsResponse contains all ingestion jobs.
type ListIngestJobsResponse struct {
	Jobs []*IngestJobSummary `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
}

func (x *ListIngestJobsResponse) GetJobs() []*IngestJobSummary {
	if x != nil {
		return x.Jobs
	}
	return nil
}

// IngestJobSummary is a summary of an ingestion job.
type IngestJobSummary struct {
	JobId         string          `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	FilePath      string          `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Database      string          `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string          `protobuf:"bytes,4,opt,name=collection,proto3" json:"collection,omitempty"`
	Status        IngestJobStatus `protobuf:"varint,5,opt,name=status,proto3,enum=mongocore.v1.IngestJobStatus" json:"status,omitempty"`
	TotalRows     int64           `protobuf:"varint,6,opt,name=total_rows,json=totalRows,proto3" json:"total_rows,omitempty"`
	RowsProcessed int64           `protobuf:"varint,7,opt,name=rows_processed,json=rowsProcessed,proto3" json:"rows_processed,omitempty"`
}

func (x *IngestJobSummary) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *IngestJobSummary) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *IngestJobSummary) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *IngestJobSummary) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *IngestJobSummary) GetStatus() IngestJobStatus {
	if x != nil {
		return x.Status
	}
	return IngestJobStatus_INGEST_JOB_STATUS_RUNNING
}

func (x *IngestJobSummary) GetTotalRows() int64 {
	if x != nil {
		return x.TotalRows
	}
	return 0
}

func (x *IngestJobSummary) GetRowsProcessed() int64 {
	if x != nil {
		return x.RowsProcessed
	}
	return 0
}

// CancelIngestRequest cancels an ingestion job.
type CancelIngestRequest struct {
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
}

func (x *CancelIngestRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// CancelIngestResponse indicates whether cancellation succeeded.
type CancelIngestResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *CancelIngestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// WatchDirectoryRequest starts watching a directory for new files to ingest.
type WatchDirectoryRequest struct {
	Path             string           `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	FilePattern      string           `protobuf:"bytes,2,opt,name=file_pattern,json=filePattern,proto3" json:"file_pattern,omitempty"`
	Database         string           `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	Collection       string           `protobuf:"bytes,4,opt,name=collection,proto3" json:"collection,omitempty"`
	ConflictStrategy ConflictStrategy `protobuf:"varint,5,opt,name=conflict_strategy,json=conflictStrategy,proto3,enum=mongocore.v1.ConflictStrategy" json:"conflict_strategy,omitempty"`
	DedupKey         []string         `protobuf:"bytes,6,rep,name=dedup_key,json=dedupKey,proto3" json:"dedup_key,omitempty"`
}

func (x *WatchDirectoryRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WatchDirectoryRequest) GetFilePattern() string {
	if x != nil {
		return x.FilePattern
	}
	return ""
}

func (x *WatchDirectoryRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *WatchDirectoryRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *WatchDirectoryRequest) GetConflictStrategy() ConflictStrategy {
	if x != nil {
		return x.ConflictStrategy
	}
	return ConflictStrategy_CONFLICT_STRATEGY_SKIP
}

func (x *WatchDirectoryRequest) GetDedupKey() []string {
	if x != nil {
		return x.DedupKey
	}
	return nil
}

// WatchDirectoryResponse returns the watch ID.
type WatchDirectoryResponse struct {
	WatchId string `protobuf:"bytes,1,opt,name=watch_id,json=watchId,proto3" json:"watch_id,omitempty"`
}

func (x *WatchDirectoryResponse) GetWatchId() string {
	if x != nil {
		return x.WatchId
	}
	return ""
}

// StopWatchRequest stops a directory watch.
type StopWatchRequest struct {
	WatchId string `protobuf:"bytes,1,opt,name=watch_id,json=watchId,proto3" json:"watch_id,omitempty"`
}

func (x *StopWatchRequest) GetWatchId() string {
	if x != nil {
		return x.WatchId
	}
	return ""
}

// StopWatchResponse indicates whether the watch was stopped.
type StopWatchResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *StopWatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}
