// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: mongocore/v1/mongocore.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MongoCore_Find_FullMethodName              = "/mongocore.v1.MongoCore/Find"
	MongoCore_FindOne_FullMethodName           = "/mongocore.v1.MongoCore/FindOne"
	MongoCore_Insert_FullMethodName            = "/mongocore.v1.MongoCore/Insert"
	MongoCore_InsertMany_FullMethodName        = "/mongocore.v1.MongoCore/InsertMany"
	MongoCore_Update_FullMethodName            = "/mongocore.v1.MongoCore/Update"
	MongoCore_UpdateMany_FullMethodName        = "/mongocore.v1.MongoCore/UpdateMany"
	MongoCore_Delete_FullMethodName            = "/mongocore.v1.MongoCore/Delete"
	MongoCore_DeleteMany_FullMethodName        = "/mongocore.v1.MongoCore/DeleteMany"
	MongoCore_FindAndModify_FullMethodName     = "/mongocore.v1.MongoCore/FindAndModify"
	MongoCore_Aggregate_FullMethodName         = "/mongocore.v1.MongoCore/Aggregate"
	MongoCore_BeginTransaction_FullMethodName  = "/mongocore.v1.MongoCore/BeginTransaction"
	MongoCore_CommitTransaction_FullMethodName = "/mongocore.v1.MongoCore/CommitTransaction"
	MongoCore_AbortTransaction_FullMethodName  = "/mongocore.v1.MongoCore/AbortTransaction"
	MongoCore_CreateCollection_FullMethodName  = "/mongocore.v1.MongoCore/CreateCollection"
	MongoCore_CreateIndex_FullMethodName       = "/mongocore.v1.MongoCore/CreateIndex"
	MongoCore_ListDatabases_FullMethodName     = "/mongocore.v1.MongoCore/ListDatabases"
	MongoCore_ListCollections_FullMethodName   = "/mongocore.v1.MongoCore/ListCollections"
	MongoCore_Search_FullMethodName            = "/mongocore.v1.MongoCore/Search"
	MongoCore_Watch_FullMethodName             = "/mongocore.v1.MongoCore/Watch"
	MongoCore_RunCommand_FullMethodName        = "/mongocore.v1.MongoCore/RunCommand"
	MongoCore_GetAnalytics_FullMethodName      = "/mongocore.v1.MongoCore/GetAnalytics"
)

// MongoCoreClient is the client API for MongoCore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MongoCoreClient interface {
	// CRUD
	Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error)
	FindOne(ctx context.Context, in *FindOneRequest, opts ...grpc.CallOption) (*FindOneResponse, error)
	Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error)
	InsertMany(ctx context.Context, in *InsertManyRequest, opts ...grpc.CallOption) (*InsertManyResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	UpdateMany(ctx context.Context, in *UpdateManyRequest, opts ...grpc.CallOption) (*UpdateManyResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	DeleteMany(ctx context.Context, in *DeleteManyRequest, opts ...grpc.CallOption) (*DeleteManyResponse, error)
	FindAndModify(ctx context.Context, in *FindAndModifyRequest, opts ...grpc.CallOption) (*FindAndModifyResponse, error)
	// Aggregation
	Aggregate(ctx context.Context, in *AggregateRequest, opts ...grpc.CallOption) (*AggregateResponse, error)
	// Transactions
	BeginTransaction(ctx context.Context, in *BeginTransactionRequest, opts ...grpc.CallOption) (*BeginTransactionResponse, error)
	CommitTransaction(ctx context.Context, in *CommitTransactionRequest, opts ...grpc.CallOption) (*CommitTransactionResponse, error)
	AbortTransaction(ctx context.Context, in *AbortTransactionRequest, opts ...grpc.CallOption) (*AbortTransactionResponse, error)
	// Admin
	CreateCollection(ctx context.Context, in *CreateCollectionRequest, opts ...grpc.CallOption) (*CreateCollectionResponse, error)
	CreateIndex(ctx context.Context, in *CreateIndexRequest, opts ...grpc.CallOption) (*CreateIndexResponse, error)
	// Introspection
	ListDatabases(ctx context.Context, in *ListDatabasesRequest, opts ...grpc.CallOption) (*ListDatabasesResponse, error)
	ListCollections(ctx context.Context, in *ListCollectionsRequest, opts ...grpc.CallOption) (*ListCollectionsResponse, error)
	// Search
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// Streaming
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error)
	// Raw Passthrough
	RunCommand(ctx context.Context, in *RunCommandRequest, opts ...grpc.CallOption) (*RunCommandResponse, error)
	// Analytics
	GetAnalytics(ctx context.Context, in *GetAnalyticsRequest, opts ...grpc.CallOption) (*GetAnalyticsResponse, error)
}

type mongoCoreClient struct {
	cc grpc.ClientConnInterface
}

func NewMongoCoreClient(cc grpc.ClientConnInterface) MongoCoreClient {
	return &mongoCoreClient{cc}
}

func (c *mongoCoreClient) Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindResponse)
	err := c.cc.Invoke(ctx, MongoCore_Find_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mongoCoreClient) FindOne(ctx context.Context, in *FindOneRequest, opts ...grpc.CallOption) (*FindOneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindOneResponse)
	err := c.cc.Invoke(ctx, MongoCore_FindOne_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mongoCoreClient) Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, MongoCore_Insert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mongoCoreClient) InsertMany(ctx context.Context, in *InsertManyRequest, opts ...grpc.CallOption) (*InsertManyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertManyResponse)
	err := c.cc.Invoke(ctx, MongoCore_InsertMany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mongoCoreClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, MongoCore_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mongoCoreClient) UpdateMany(ctx context.Context, in *UpdateManyRequest, opts ...grpc.CallOption) (*UpdateManyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateManyResponse)
	err := c.cc.Invoke(ctx, MongoCore_UpdateMany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mongoCoreClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, MongoCore_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mongoCoreClient) DeleteMany(ctx context.Context, in *DeleteManyRequest, opts ...grpc.CallOption) (*DeleteManyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteManyResponse)
	err := c.cc.Invoke(ctx, MongoCore_DeleteMany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mongoCoreClient) FindAndModify(ctx context.Context, in *FindAndModifyRequest, opts ...grpc.CallOption) (*FindAndModifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindAndModifyResponse)
	err := c.cc.Invoke(ctx, MongoCore_FindAndModify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mongoCoreClient) Aggregate(ctx context.Context, in *AggregateRequest, opts ...grpc.CallOption) (*AggregateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AggregateResponse)
	err := c.cc.Invoke(ctx, MongoCore_Aggregate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mongoCoreClient) BeginTransaction(ctx context.Context, in *BeginTransactionRequest, opts ...grpc.CallOption) (*BeginTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginTransactionResponse)
	err := c.cc.Invoke(ctx, MongoCore_BeginTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mongoCoreClient) CommitTransaction(ctx context.Context, in *CommitTransactionRequest, opts ...grpc.CallOption) (*CommitTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitTransactionResponse)
	err := c.cc.Invoke(ctx, MongoCore_CommitTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mongoCoreClient) AbortTransaction(ctx context.Context, in *AbortTransactionRequest, opts ...grpc.CallOption) (*AbortTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortTransactionResponse)
	err := c.cc.Invoke(ctx, MongoCore_AbortTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mongoCoreClient) CreateCollection(ctx context.Context, in *CreateCollectionRequest, opts ...grpc.CallOption) (*CreateCollectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCollectionResponse)
	err := c.cc.Invoke(ctx, MongoCore_CreateCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mongoCoreClient) CreateIndex(ctx context.Context, in *CreateIndexRequest, opts ...grpc.CallOption) (*CreateIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateIndexResponse)
	err := c.cc.Invoke(ctx, MongoCore_CreateIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mongoCoreClient) ListDatabases(ctx context.Context, in *ListDatabasesRequest, opts ...grpc.CallOption) (*ListDatabasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDatabasesResponse)
	err := c.cc.Invoke(ctx, MongoCore_ListDatabases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mongoCoreClient) ListCollections(ctx context.Context, in *ListCollectionsRequest, opts ...grpc.CallOption) (*ListCollectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCollectionsResponse)
	err := c.cc.Invoke(ctx, MongoCore_ListCollections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mongoCoreClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, MongoCore_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mongoCoreClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MongoCore_ServiceDesc.Streams[0], MongoCore_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MongoCore_WatchClient = grpc.ServerStreamingClient[WatchEvent]

func (c *mongoCoreClient) RunCommand(ctx context.Context, in *RunCommandRequest, opts ...grpc.CallOption) (*RunCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunCommandResponse)
	err := c.cc.Invoke(ctx, MongoCore_RunCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mongoCoreClient) GetAnalytics(ctx context.Context, in *GetAnalyticsRequest, opts ...grpc.CallOption) (*GetAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAnalyticsResponse)
	err := c.cc.Invoke(ctx, MongoCore_GetAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MongoCoreServer is the server API for MongoCore service.
// All implementations must embed UnimplementedMongoCoreServer
// for forward compatibility.
type MongoCoreServer interface {
	// CRUD
	Find(context.Context, *FindRequest) (*FindResponse, error)
	FindOne(context.Context, *FindOneRequest) (*FindOneResponse, error)
	Insert(context.Context, *InsertRequest) (*InsertResponse, error)
	InsertMany(context.Context, *InsertManyRequest) (*InsertManyResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	UpdateMany(context.Context, *UpdateManyRequest) (*UpdateManyResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	DeleteMany(context.Context, *DeleteManyRequest) (*DeleteManyResponse, error)
	FindAndModify(context.Context, *FindAndModifyRequest) (*FindAndModifyResponse, error)
	// Aggregation
	Aggregate(context.Context, *AggregateRequest) (*AggregateResponse, error)
	// Transactions
	BeginTransaction(context.Context, *BeginTransactionRequest) (*BeginTransactionResponse, error)
	CommitTransaction(context.Context, *CommitTransactionRequest) (*CommitTransactionResponse, error)
	AbortTransaction(context.Context, *AbortTransactionRequest) (*AbortTransactionResponse, error)
	// Admin
	CreateCollection(context.Context, *CreateCollectionRequest) (*CreateCollectionResponse, error)
	CreateIndex(context.Context, *CreateIndexRequest) (*CreateIndexResponse, error)
	// Introspection
	ListDatabases(context.Context, *ListDatabasesRequest) (*ListDatabasesResponse, error)
	ListCollections(context.Context, *ListCollectionsRequest) (*ListCollectionsResponse, error)
	// Search
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// Streaming
	Watch(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error
	// Raw Passthrough
	RunCommand(context.Context, *RunCommandRequest) (*RunCommandResponse, error)
	// Analytics
	GetAnalytics(context.Context, *GetAnalyticsRequest) (*GetAnalyticsResponse, error)
	mustEmbedUnimplementedMongoCoreServer()
}

// UnimplementedMongoCoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMongoCoreServer struct{}

func (UnimplementedMongoCoreServer) Find(context.Context, *FindRequest) (*FindResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Find not implemented")
}
func (UnimplementedMongoCoreServer) FindOne(context.Context, *FindOneRequest) (*FindOneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindOne not implemented")
}
func (UnimplementedMongoCoreServer) Insert(context.Context, *InsertRequest) (*InsertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedMongoCoreServer) InsertMany(context.Context, *InsertManyRequest) (*InsertManyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertMany not implemented")
}
func (UnimplementedMongoCoreServer) Update(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedMongoCoreServer) UpdateMany(context.Context, *UpdateManyRequest) (*UpdateManyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMany not implemented")
}
func (UnimplementedMongoCoreServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedMongoCoreServer) DeleteMany(context.Context, *DeleteManyRequest) (*DeleteManyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMany not implemented")
}
func (UnimplementedMongoCoreServer) FindAndModify(context.Context, *FindAndModifyRequest) (*FindAndModifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindAndModify not implemented")
}
func (UnimplementedMongoCoreServer) Aggregate(context.Context, *AggregateRequest) (*AggregateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Aggregate not implemented")
}
func (UnimplementedMongoCoreServer) BeginTransaction(context.Context, *BeginTransactionRequest) (*BeginTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginTransaction not implemented")
}
func (UnimplementedMongoCoreServer) CommitTransaction(context.Context, *CommitTransactionRequest) (*CommitTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitTransaction not implemented")
}
func (UnimplementedMongoCoreServer) AbortTransaction(context.Context, *AbortTransactionRequest) (*AbortTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AbortTransaction not implemented")
}
func (UnimplementedMongoCoreServer) CreateCollection(context.Context, *CreateCollectionRequest) (*CreateCollectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCollection not implemented")
}
func (UnimplementedMongoCoreServer) CreateIndex(context.Context, *CreateIndexRequest) (*CreateIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateIndex not implemented")
}
func (UnimplementedMongoCoreServer) ListDatabases(context.Context, *ListDatabasesRequest) (*ListDatabasesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDatabases not implemented")
}
func (UnimplementedMongoCoreServer) ListCollections(context.Context, *ListCollectionsRequest) (*ListCollectionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCollections not implemented")
}
func (UnimplementedMongoCoreServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedMongoCoreServer) Watch(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedMongoCoreServer) RunCommand(context.Context, *RunCommandRequest) (*RunCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunCommand not implemented")
}
func (UnimplementedMongoCoreServer) GetAnalytics(context.Context, *GetAnalyticsRequest) (*GetAnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAnalytics not implemented")
}
func (UnimplementedMongoCoreServer) mustEmbedUnimplementedMongoCoreServer() {}
func (UnimplementedMongoCoreServer) testEmbeddedByValue()                   {}

// UnsafeMongoCoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MongoCoreServer will
// result in compilation errors.
type UnsafeMongoCoreServer interface {
	mustEmbedUnimplementedMongoCoreServer()
}

func RegisterMongoCoreServer(s grpc.ServiceRegistrar, srv MongoCoreServer) {
	// If the following call panics, it indicates UnimplementedMongoCoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MongoCore_ServiceDesc, srv)
}

func _MongoCore_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoCoreServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MongoCore_Find_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoCoreServer).Find(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MongoCore_FindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoCoreServer).FindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MongoCore_FindOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoCoreServer).FindOne(ctx, req.(*FindOneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MongoCore_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoCoreServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MongoCore_Insert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoCoreServer).Insert(ctx, req.(*InsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MongoCore_InsertMany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertManyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoCoreServer).InsertMany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MongoCore_InsertMany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoCoreServer).InsertMany(ctx, req.(*InsertManyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MongoCore_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoCoreServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MongoCore_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoCoreServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MongoCore_UpdateMany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateManyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoCoreServer).UpdateMany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MongoCore_UpdateMany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoCoreServer).UpdateMany(ctx, req.(*UpdateManyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MongoCore_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoCoreServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MongoCore_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoCoreServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MongoCore_DeleteMany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteManyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoCoreServer).DeleteMany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MongoCore_DeleteMany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoCoreServer).DeleteMany(ctx, req.(*DeleteManyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MongoCore_FindAndModify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAndModifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoCoreServer).FindAndModify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MongoCore_FindAndModify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoCoreServer).FindAndModify(ctx, req.(*FindAndModifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MongoCore_Aggregate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggregateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoCoreServer).Aggregate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MongoCore_Aggregate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoCoreServer).Aggregate(ctx, req.(*AggregateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MongoCore_BeginTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoCoreServer).BeginTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MongoCore_BeginTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoCoreServer).BeginTransaction(ctx, req.(*BeginTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MongoCore_CommitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoCoreServer).CommitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MongoCore_CommitTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoCoreServer).CommitTransaction(ctx, req.(*CommitTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MongoCore_AbortTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoCoreServer).AbortTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MongoCore_AbortTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoCoreServer).AbortTransaction(ctx, req.(*AbortTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MongoCore_CreateCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoCoreServer).CreateCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MongoCore_CreateCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoCoreServer).CreateCollection(ctx, req.(*CreateCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MongoCore_CreateIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoCoreServer).CreateIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MongoCore_CreateIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoCoreServer).CreateIndex(ctx, req.(*CreateIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MongoCore_ListDatabases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDatabasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoCoreServer).ListDatabases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MongoCore_ListDatabases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoCoreServer).ListDatabases(ctx, req.(*ListDatabasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MongoCore_ListCollections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCollectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoCoreServer).ListCollections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MongoCore_ListCollections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoCoreServer).ListCollections(ctx, req.(*ListCollectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MongoCore_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoCoreServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MongoCore_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoCoreServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MongoCore_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MongoCoreServer).Watch(m, &grpc.GenericServerStream[WatchRequest, WatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MongoCore_WatchServer = grpc.ServerStreamingServer[WatchEvent]

func _MongoCore_RunCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoCoreServer).RunCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MongoCore_RunCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoCoreServer).RunCommand(ctx, req.(*RunCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MongoCore_GetAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoCoreServer).GetAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MongoCore_GetAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoCoreServer).GetAnalytics(ctx, req.(*GetAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MongoCore_ServiceDesc is the grpc.ServiceDesc for MongoCore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MongoCore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mongocore.v1.MongoCore",
	HandlerType: (*MongoCoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Find",
			Handler:    _MongoCore_Find_Handler,
		},
		{
			MethodName: "FindOne",
			Handler:    _MongoCore_FindOne_Handler,
		},
		{
			MethodName: "Insert",
			Handler:    _MongoCore_Insert_Handler,
		},
		{
			MethodName: "InsertMany",
			Handler:    _MongoCore_InsertMany_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _MongoCore_Update_Handler,
		},
		{
			MethodName: "UpdateMany",
			Handler:    _MongoCore_UpdateMany_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _MongoCore_Delete_Handler,
		},
		{
			MethodName: "DeleteMany",
			Handler:    _MongoCore_DeleteMany_Handler,
		},
		{
			MethodName: "FindAndModify",
			Handler:    _MongoCore_FindAndModify_Handler,
		},
		{
			MethodName: "Aggregate",
			Handler:    _MongoCore_Aggregate_Handler,
		},
		{
			MethodName: "BeginTransaction",
			Handler:    _MongoCore_BeginTransaction_Handler,
		},
		{
			MethodName: "CommitTransaction",
			Handler:    _MongoCore_CommitTransaction_Handler,
		},
		{
			MethodName: "AbortTransaction",
			Handler:    _MongoCore_AbortTransaction_Handler,
		},
		{
			MethodName: "CreateCollection",
			Handler:    _MongoCore_CreateCollection_Handler,
		},
		{
			MethodName: "CreateIndex",
			Handler:    _MongoCore_CreateIndex_Handler,
		},
		{
			MethodName: "ListDatabases",
			Handler:    _MongoCore_ListDatabases_Handler,
		},
		{
			MethodName: "ListCollections",
			Handler:    _MongoCore_ListCollections_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _MongoCore_Search_Handler,
		},
		{
			MethodName: "RunCommand",
			Handler:    _MongoCore_RunCommand_Handler,
		},
		{
			MethodName: "GetAnalytics",
			Handler:    _MongoCore_GetAnalytics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _MongoCore_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mongocore/v1/mongocore.proto",
}
