// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: mongocore/v1/mongocore.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchEvent_OperationType int32

const (
	WatchEvent_INSERT     WatchEvent_OperationType = 0
	WatchEvent_UPDATE     WatchEvent_OperationType = 1
	WatchEvent_DELETE     WatchEvent_OperationType = 2
	WatchEvent_REPLACE    WatchEvent_OperationType = 3
	WatchEvent_INVALIDATE WatchEvent_OperationType = 4
)

// Enum value maps for WatchEvent_OperationType.
var (
	WatchEvent_OperationType_name = map[int32]string{
		0: "INSERT",
		1: "UPDATE",
		2: "DELETE",
		3: "REPLACE",
		4: "INVALIDATE",
	}
	WatchEvent_OperationType_value = map[string]int32{
		"INSERT":     0,
		"UPDATE":     1,
		"DELETE":     2,
		"REPLACE":    3,
		"INVALIDATE": 4,
	}
)

func (x WatchEvent_OperationType) Enum() *WatchEvent_OperationType {
	p := new(WatchEvent_OperationType)
	*p = x
	return p
}

func (x WatchEvent_OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchEvent_OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_mongocore_v1_mongocore_proto_enumTypes[0].Descriptor()
}

func (WatchEvent_OperationType) Type() protoreflect.EnumType {
	return &file_mongocore_v1_mongocore_proto_enumTypes[0]
}

func (x WatchEvent_OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchEvent_OperationType.Descriptor instead.
func (WatchEvent_OperationType) EnumDescriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{35, 0}
}

type FindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Filter        *Filter                `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Options       *FindOptions           `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	TransactionId *string                `protobuf:"bytes,5,opt,name=transaction_id,json=transactionId,proto3,oneof" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRequest) Reset() {
	*x = FindRequest{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRequest) ProtoMessage() {}

func (x *FindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRequest.ProtoReflect.Descriptor instead.
func (*FindRequest) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{0}
}

func (x *FindRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *FindRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *FindRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *FindRequest) GetOptions() *FindOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *FindRequest) GetTransactionId() string {
	if x != nil && x.TransactionId != nil {
		return *x.TransactionId
	}
	return ""
}

type FindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*Document            `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	Metadata      *ResponseMetadata      `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindResponse) Reset() {
	*x = FindResponse{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindResponse) ProtoMessage() {}

func (x *FindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindResponse.ProtoReflect.Descriptor instead.
func (*FindResponse) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{1}
}

func (x *FindResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *FindResponse) GetMetadata() *ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type FindOneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Filter        *Filter                `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Options       *FindOptions           `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	TransactionId *string                `protobuf:"bytes,5,opt,name=transaction_id,json=transactionId,proto3,oneof" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindOneRequest) Reset() {
	*x = FindOneRequest{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOneRequest) ProtoMessage() {}

func (x *FindOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOneRequest.ProtoReflect.Descriptor instead.
func (*FindOneRequest) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{2}
}

func (x *FindOneRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *FindOneRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *FindOneRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *FindOneRequest) GetOptions() *FindOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *FindOneRequest) GetTransactionId() string {
	if x != nil && x.TransactionId != nil {
		return *x.TransactionId
	}
	return ""
}

type FindOneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3,oneof" json:"document,omitempty"`
	Metadata      *ResponseMetadata      `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindOneResponse) Reset() {
	*x = FindOneResponse{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOneResponse) ProtoMessage() {}

func (x *FindOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOneResponse.ProtoReflect.Descriptor instead.
func (*FindOneResponse) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{3}
}

func (x *FindOneResponse) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *FindOneResponse) GetMetadata() *ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type InsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Document      *Document              `protobuf:"bytes,3,opt,name=document,proto3" json:"document,omitempty"`
	TransactionId *string                `protobuf:"bytes,4,opt,name=transaction_id,json=transactionId,proto3,oneof" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{4}
}

func (x *InsertRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *InsertRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *InsertRequest) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *InsertRequest) GetTransactionId() string {
	if x != nil && x.TransactionId != nil {
		return *x.TransactionId
	}
	return ""
}

type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InsertedId    string                 `protobuf:"bytes,1,opt,name=inserted_id,json=insertedId,proto3" json:"inserted_id,omitempty"` // Stringified ObjectId or equivalent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{5}
}

func (x *InsertResponse) GetInsertedId() string {
	if x != nil {
		return x.InsertedId
	}
	return ""
}

type InsertManyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Documents     []*Document            `protobuf:"bytes,3,rep,name=documents,proto3" json:"documents,omitempty"`
	TransactionId *string                `protobuf:"bytes,4,opt,name=transaction_id,json=transactionId,proto3,oneof" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertManyRequest) Reset() {
	*x = InsertManyRequest{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertManyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertManyRequest) ProtoMessage() {}

func (x *InsertManyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertManyRequest.ProtoReflect.Descriptor instead.
func (*InsertManyRequest) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{6}
}

func (x *InsertManyRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *InsertManyRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *InsertManyRequest) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *InsertManyRequest) GetTransactionId() string {
	if x != nil && x.TransactionId != nil {
		return *x.TransactionId
	}
	return ""
}

type InsertManyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InsertedIds   []string               `protobuf:"bytes,1,rep,name=inserted_ids,json=insertedIds,proto3" json:"inserted_ids,omitempty"`
	InsertedCount int64                  `protobuf:"varint,2,opt,name=inserted_count,json=insertedCount,proto3" json:"inserted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertManyResponse) Reset() {
	*x = InsertManyResponse{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertManyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertManyResponse) ProtoMessage() {}

func (x *InsertManyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertManyResponse.ProtoReflect.Descriptor instead.
func (*InsertManyResponse) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{7}
}

func (x *InsertManyResponse) GetInsertedIds() []string {
	if x != nil {
		return x.InsertedIds
	}
	return nil
}

func (x *InsertManyResponse) GetInsertedCount() int64 {
	if x != nil {
		return x.InsertedCount
	}
	return 0
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Filter        *Filter                `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Update        *Document              `protobuf:"bytes,4,opt,name=update,proto3" json:"update,omitempty"` // BSON update document (e.g. {$set: {...}})
	Upsert        bool                   `protobuf:"varint,5,opt,name=upsert,proto3" json:"upsert,omitempty"`
	TransactionId *string                `protobuf:"bytes,6,opt,name=transaction_id,json=transactionId,proto3,oneof" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *UpdateRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *UpdateRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *UpdateRequest) GetUpdate() *Document {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *UpdateRequest) GetUpsert() bool {
	if x != nil {
		return x.Upsert
	}
	return false
}

func (x *UpdateRequest) GetTransactionId() string {
	if x != nil && x.TransactionId != nil {
		return *x.TransactionId
	}
	return ""
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchedCount  int64                  `protobuf:"varint,1,opt,name=matched_count,json=matchedCount,proto3" json:"matched_count,omitempty"`
	ModifiedCount int64                  `protobuf:"varint,2,opt,name=modified_count,json=modifiedCount,proto3" json:"modified_count,omitempty"`
	UpsertedId    *string                `protobuf:"bytes,3,opt,name=upserted_id,json=upsertedId,proto3,oneof" json:"upserted_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateResponse) GetMatchedCount() int64 {
	if x != nil {
		return x.MatchedCount
	}
	return 0
}

func (x *UpdateResponse) GetModifiedCount() int64 {
	if x != nil {
		return x.ModifiedCount
	}
	return 0
}

func (x *UpdateResponse) GetUpsertedId() string {
	if x != nil && x.UpsertedId != nil {
		return *x.UpsertedId
	}
	return ""
}

type UpdateManyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Filter        *Filter                `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Update        *Document              `protobuf:"bytes,4,opt,name=update,proto3" json:"update,omitempty"`
	Upsert        bool                   `protobuf:"varint,5,opt,name=upsert,proto3" json:"upsert,omitempty"`
	TransactionId *string                `protobuf:"bytes,6,opt,name=transaction_id,json=transactionId,proto3,oneof" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateManyRequest) Reset() {
	*x = UpdateManyRequest{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateManyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateManyRequest) ProtoMessage() {}

func (x *UpdateManyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateManyRequest.ProtoReflect.Descriptor instead.
func (*UpdateManyRequest) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateManyRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *UpdateManyRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *UpdateManyRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *UpdateManyRequest) GetUpdate() *Document {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *UpdateManyRequest) GetUpsert() bool {
	if x != nil {
		return x.Upsert
	}
	return false
}

func (x *UpdateManyRequest) GetTransactionId() string {
	if x != nil && x.TransactionId != nil {
		return *x.TransactionId
	}
	return ""
}

type UpdateManyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchedCount  int64                  `protobuf:"varint,1,opt,name=matched_count,json=matchedCount,proto3" json:"matched_count,omitempty"`
	ModifiedCount int64                  `protobuf:"varint,2,opt,name=modified_count,json=modifiedCount,proto3" json:"modified_count,omitempty"`
	UpsertedId    *string                `protobuf:"bytes,3,opt,name=upserted_id,json=upsertedId,proto3,oneof" json:"upserted_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateManyResponse) Reset() {
	*x = UpdateManyResponse{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateManyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateManyResponse) ProtoMessage() {}

func (x *UpdateManyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateManyResponse.ProtoReflect.Descriptor instead.
func (*UpdateManyResponse) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateManyResponse) GetMatchedCount() int64 {
	if x != nil {
		return x.MatchedCount
	}
	return 0
}

func (x *UpdateManyResponse) GetModifiedCount() int64 {
	if x != nil {
		return x.ModifiedCount
	}
	return 0
}

func (x *UpdateManyResponse) GetUpsertedId() string {
	if x != nil && x.UpsertedId != nil {
		return *x.UpsertedId
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Filter        *Filter                `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	TransactionId *string                `protobuf:"bytes,4,opt,name=transaction_id,json=transactionId,proto3,oneof" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *DeleteRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *DeleteRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *DeleteRequest) GetTransactionId() string {
	if x != nil && x.TransactionId != nil {
		return *x.TransactionId
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int64                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteResponse) GetDeletedCount() int64 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

type DeleteManyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Filter        *Filter                `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	TransactionId *string                `protobuf:"bytes,4,opt,name=transaction_id,json=transactionId,proto3,oneof" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteManyRequest) Reset() {
	*x = DeleteManyRequest{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteManyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteManyRequest) ProtoMessage() {}

func (x *DeleteManyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteManyRequest.ProtoReflect.Descriptor instead.
func (*DeleteManyRequest) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteManyRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *DeleteManyRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *DeleteManyRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *DeleteManyRequest) GetTransactionId() string {
	if x != nil && x.TransactionId != nil {
		return *x.TransactionId
	}
	return ""
}

type DeleteManyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int64                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteManyResponse) Reset() {
	*x = DeleteManyResponse{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteManyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteManyResponse) ProtoMessage() {}

func (x *DeleteManyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteManyResponse.ProtoReflect.Descriptor instead.
func (*DeleteManyResponse) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteManyResponse) GetDeletedCount() int64 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

type FindAndModifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Filter        *Filter                `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Update        *Document              `protobuf:"bytes,4,opt,name=update,proto3" json:"update,omitempty"`
	Options       *FindAndModifyOptions  `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	TransactionId *string                `protobuf:"bytes,6,opt,name=transaction_id,json=transactionId,proto3,oneof" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAndModifyRequest) Reset() {
	*x = FindAndModifyRequest{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAndModifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAndModifyRequest) ProtoMessage() {}

func (x *FindAndModifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAndModifyRequest.ProtoReflect.Descriptor instead.
func (*FindAndModifyRequest) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{16}
}

func (x *FindAndModifyRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *FindAndModifyRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *FindAndModifyRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *FindAndModifyRequest) GetUpdate() *Document {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *FindAndModifyRequest) GetOptions() *FindAndModifyOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *FindAndModifyRequest) GetTransactionId() string {
	if x != nil && x.TransactionId != nil {
		return *x.TransactionId
	}
	return ""
}

type FindAndModifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3,oneof" json:"document,omitempty"` // The document before or after modification
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAndModifyResponse) Reset() {
	*x = FindAndModifyResponse{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAndModifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAndModifyResponse) ProtoMessage() {}

func (x *FindAndModifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAndModifyResponse.ProtoReflect.Descriptor instead.
func (*FindAndModifyResponse) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{17}
}

func (x *FindAndModifyResponse) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

type AggregateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Pipeline      *Pipeline              `protobuf:"bytes,3,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	TransactionId *string                `protobuf:"bytes,4,opt,name=transaction_id,json=transactionId,proto3,oneof" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateRequest) Reset() {
	*x = AggregateRequest{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateRequest) ProtoMessage() {}

func (x *AggregateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateRequest.ProtoReflect.Descriptor instead.
func (*AggregateRequest) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{18}
}

func (x *AggregateRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *AggregateRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *AggregateRequest) GetPipeline() *Pipeline {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

func (x *AggregateRequest) GetTransactionId() string {
	if x != nil && x.TransactionId != nil {
		return *x.TransactionId
	}
	return ""
}

type AggregateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*Document            `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	Metadata      *ResponseMetadata      `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateResponse) Reset() {
	*x = AggregateResponse{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateResponse) ProtoMessage() {}

func (x *AggregateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateResponse.ProtoReflect.Descriptor instead.
func (*AggregateResponse) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{19}
}

func (x *AggregateResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *AggregateResponse) GetMetadata() *ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type BeginTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginTransactionRequest) Reset() {
	*x = BeginTransactionRequest{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTransactionRequest) ProtoMessage() {}

func (x *BeginTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTransactionRequest.ProtoReflect.Descriptor instead.
func (*BeginTransactionRequest) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{20}
}

func (x *BeginTransactionRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

type BeginTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginTransactionResponse) Reset() {
	*x = BeginTransactionResponse{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTransactionResponse) ProtoMessage() {}

func (x *BeginTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTransactionResponse.ProtoReflect.Descriptor instead.
func (*BeginTransactionResponse) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{21}
}

func (x *BeginTransactionResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type CommitTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitTransactionRequest) Reset() {
	*x = CommitTransactionRequest{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTransactionRequest) ProtoMessage() {}

func (x *CommitTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTransactionRequest.ProtoReflect.Descriptor instead.
func (*CommitTransactionRequest) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{22}
}

func (x *CommitTransactionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type CommitTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitTransactionResponse) Reset() {
	*x = CommitTransactionResponse{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTransactionResponse) ProtoMessage() {}

func (x *CommitTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTransactionResponse.ProtoReflect.Descriptor instead.
func (*CommitTransactionResponse) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{23}
}

type AbortTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortTransactionRequest) Reset() {
	*x = AbortTransactionRequest{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortTransactionRequest) ProtoMessage() {}

func (x *AbortTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortTransactionRequest.ProtoReflect.Descriptor instead.
func (*AbortTransactionRequest) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{24}
}

func (x *AbortTransactionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type AbortTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortTransactionResponse) Reset() {
	*x = AbortTransactionResponse{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortTransactionResponse) ProtoMessage() {}

func (x *AbortTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortTransactionResponse.ProtoReflect.Descriptor instead.
func (*AbortTransactionResponse) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{25}
}

type CreateCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionRequest) Reset() {
	*x = CreateCollectionRequest{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionRequest) ProtoMessage() {}

func (x *CreateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionRequest.ProtoReflect.Descriptor instead.
func (*CreateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{26}
}

func (x *CreateCollectionRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *CreateCollectionRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

type CreateCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionResponse) Reset() {
	*x = CreateCollectionResponse{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionResponse) ProtoMessage() {}

func (x *CreateCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionResponse.ProtoReflect.Descriptor instead.
func (*CreateCollectionResponse) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{27}
}

type CreateIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Keys          *Document              `protobuf:"bytes,3,opt,name=keys,proto3" json:"keys,omitempty"` // BSON document specifying index keys
	Options       *IndexOptions          `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIndexRequest) Reset() {
	*x = CreateIndexRequest{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIndexRequest) ProtoMessage() {}

func (x *CreateIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIndexRequest.ProtoReflect.Descriptor instead.
func (*CreateIndexRequest) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{28}
}

func (x *CreateIndexRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *CreateIndexRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *CreateIndexRequest) GetKeys() *Document {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *CreateIndexRequest) GetOptions() *IndexOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type CreateIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexName     string                 `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIndexResponse) Reset() {
	*x = CreateIndexResponse{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIndexResponse) ProtoMessage() {}

func (x *CreateIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIndexResponse.ProtoReflect.Descriptor instead.
func (*CreateIndexResponse) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{29}
}

func (x *CreateIndexResponse) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

type ListDatabasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatabasesRequest) Reset() {
	*x = ListDatabasesRequest{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatabasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatabasesRequest) ProtoMessage() {}

func (x *ListDatabasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatabasesRequest.ProtoReflect.Descriptor instead.
func (*ListDatabasesRequest) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{30}
}

type ListDatabasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Databases     []string               `protobuf:"bytes,1,rep,name=databases,proto3" json:"databases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatabasesResponse) Reset() {
	*x = ListDatabasesResponse{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatabasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatabasesResponse) ProtoMessage() {}

func (x *ListDatabasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatabasesResponse.ProtoReflect.Descriptor instead.
func (*ListDatabasesResponse) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{31}
}

func (x *ListDatabasesResponse) GetDatabases() []string {
	if x != nil {
		return x.Databases
	}
	return nil
}

type ListCollectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsRequest) Reset() {
	*x = ListCollectionsRequest{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsRequest) ProtoMessage() {}

func (x *ListCollectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionsRequest) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{32}
}

func (x *ListCollectionsRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

type ListCollectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collections   []string               `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsResponse) Reset() {
	*x = ListCollectionsResponse{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsResponse) ProtoMessage() {}

func (x *ListCollectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsResponse.ProtoReflect.Descriptor instead.
func (*ListCollectionsResponse) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{33}
}

func (x *ListCollectionsResponse) GetCollections() []string {
	if x != nil {
		return x.Collections
	}
	return nil
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Collection    *string                `protobuf:"bytes,2,opt,name=collection,proto3,oneof" json:"collection,omitempty"` // If empty, watch whole database
	Pipeline      *Pipeline              `protobuf:"bytes,3,opt,name=pipeline,proto3" json:"pipeline,omitempty"`           // Optional aggregation pipeline to filter events
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{34}
}

func (x *WatchRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *WatchRequest) GetCollection() string {
	if x != nil && x.Collection != nil {
		return *x.Collection
	}
	return ""
}

func (x *WatchRequest) GetPipeline() *Pipeline {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

type WatchEvent struct {
	state             protoimpl.MessageState   `protogen:"open.v1"`
	OperationType     WatchEvent_OperationType `protobuf:"varint,1,opt,name=operation_type,json=operationType,proto3,enum=mongocore.v1.WatchEvent_OperationType" json:"operation_type,omitempty"`
	Database          string                   `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	Collection        string                   `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	Document          *Document                `protobuf:"bytes,4,opt,name=document,proto3,oneof" json:"document,omitempty"`                                            // Full document (for insert/update/replace)
	UpdateDescription *Document                `protobuf:"bytes,5,opt,name=update_description,json=updateDescription,proto3,oneof" json:"update_description,omitempty"` // For update events: {updatedFields, removedFields}
	DocumentKey       *Document                `protobuf:"bytes,6,opt,name=document_key,json=documentKey,proto3,oneof" json:"document_key,omitempty"`                   // The _id of the affected document
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_mongocore_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEvent.ProtoReflect.Descriptor instead.
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_mongocore_proto_rawDescGZIP(), []int{35}
}

func (x *WatchEvent) GetOperationType() WatchEvent_OperationType {
	if x != nil {
		return x.OperationType
	}
	return WatchEvent_INSERT
}

func (x *WatchEvent) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *WatchEvent) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *WatchEvent) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *WatchEvent) GetUpdateDescription() *Document {
	if x != nil {
		return x.UpdateDescription
	}
	return nil
}

func (x *WatchEvent) GetDocumentKey() *Document {
	if x != nil {
		return x.DocumentKey
	}
	return nil
}

var File_mongocore_v1_mongocore_proto protoreflect.FileDescriptor

const file_mongocore_v1_mongocore_proto_rawDesc = "" +
	"\n" +
	"\x1cmongocore/v1/mongocore.proto\x12\fmongocore.v1\x1a\x18mongocore/v1/types.proto\"\xeb\x01\n" +
	"\vFindRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12,\n" +
	"\x06filter\x18\x03 \x01(\v2\x14.mongocore.v1.FilterR\x06filter\x123\n" +
	"\aoptions\x18\x04 \x01(\v2\x19.mongocore.v1.FindOptionsR\aoptions\x12*\n" +
	"\x0etransaction_id\x18\x05 \x01(\tH\x00R\rtransactionId\x88\x01\x01B\x11\n" +
	"\x0f_transaction_id\"\x80\x01\n" +
	"\fFindResponse\x124\n" +
	"\tdocuments\x18\x01 \x03(\v2\x16.mongocore.v1.DocumentR\tdocuments\x12:\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1e.mongocore.v1.ResponseMetadataR\bmetadata\"\xee\x01\n" +
	"\x0eFindOneRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12,\n" +
	"\x06filter\x18\x03 \x01(\v2\x14.mongocore.v1.FilterR\x06filter\x123\n" +
	"\aoptions\x18\x04 \x01(\v2\x19.mongocore.v1.FindOptionsR\aoptions\x12*\n" +
	"\x0etransaction_id\x18\x05 \x01(\tH\x00R\rtransactionId\x88\x01\x01B\x11\n" +
	"\x0f_transaction_id\"\x93\x01\n" +
	"\x0fFindOneResponse\x127\n" +
	"\bdocument\x18\x01 \x01(\v2\x16.mongocore.v1.DocumentH\x00R\bdocument\x88\x01\x01\x12:\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1e.mongocore.v1.ResponseMetadataR\bmetadataB\v\n" +
	"\t_document\"\xbe\x01\n" +
	"\rInsertRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x122\n" +
	"\bdocument\x18\x03 \x01(\v2\x16.mongocore.v1.DocumentR\bdocument\x12*\n" +
	"\x0etransaction_id\x18\x04 \x01(\tH\x00R\rtransactionId\x88\x01\x01B\x11\n" +
	"\x0f_transaction_id\"1\n" +
	"\x0eInsertResponse\x12\x1f\n" +
	"\vinserted_id\x18\x01 \x01(\tR\n" +
	"insertedId\"\xc4\x01\n" +
	"\x11InsertManyRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x124\n" +
	"\tdocuments\x18\x03 \x03(\v2\x16.mongocore.v1.DocumentR\tdocuments\x12*\n" +
	"\x0etransaction_id\x18\x04 \x01(\tH\x00R\rtransactionId\x88\x01\x01B\x11\n" +
	"\x0f_transaction_id\"^\n" +
	"\x12InsertManyResponse\x12!\n" +
	"\finserted_ids\x18\x01 \x03(\tR\vinsertedIds\x12%\n" +
	"\x0einserted_count\x18\x02 \x01(\x03R\rinsertedCount\"\x80\x02\n" +
	"\rUpdateRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12,\n" +
	"\x06filter\x18\x03 \x01(\v2\x14.mongocore.v1.FilterR\x06filter\x12.\n" +
	"\x06update\x18\x04 \x01(\v2\x16.mongocore.v1.DocumentR\x06update\x12\x16\n" +
	"\x06upsert\x18\x05 \x01(\bR\x06upsert\x12*\n" +
	"\x0etransaction_id\x18\x06 \x01(\tH\x00R\rtransactionId\x88\x01\x01B\x11\n" +
	"\x0f_transaction_id\"\x92\x01\n" +
	"\x0eUpdateResponse\x12#\n" +
	"\rmatched_count\x18\x01 \x01(\x03R\fmatchedCount\x12%\n" +
	"\x0emodified_count\x18\x02 \x01(\x03R\rmodifiedCount\x12$\n" +
	"\vupserted_id\x18\x03 \x01(\tH\x00R\n" +
	"upsertedId\x88\x01\x01B\x0e\n" +
	"\f_upserted_id\"\x84\x02\n" +
	"\x11UpdateManyRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12,\n" +
	"\x06filter\x18\x03 \x01(\v2\x14.mongocore.v1.FilterR\x06filter\x12.\n" +
	"\x06update\x18\x04 \x01(\v2\x16.mongocore.v1.DocumentR\x06update\x12\x16\n" +
	"\x06upsert\x18\x05 \x01(\bR\x06upsert\x12*\n" +
	"\x0etransaction_id\x18\x06 \x01(\tH\x00R\rtransactionId\x88\x01\x01B\x11\n" +
	"\x0f_transaction_id\"\x96\x01\n" +
	"\x12UpdateManyResponse\x12#\n" +
	"\rmatched_count\x18\x01 \x01(\x03R\fmatchedCount\x12%\n" +
	"\x0emodified_count\x18\x02 \x01(\x03R\rmodifiedCount\x12$\n" +
	"\vupserted_id\x18\x03 \x01(\tH\x00R\n" +
	"upsertedId\x88\x01\x01B\x0e\n" +
	"\f_upserted_id\"\xb8\x01\n" +
	"\rDeleteRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12,\n" +
	"\x06filter\x18\x03 \x01(\v2\x14.mongocore.v1.FilterR\x06filter\x12*\n" +
	"\x0etransaction_id\x18\x04 \x01(\tH\x00R\rtransactionId\x88\x01\x01B\x11\n" +
	"\x0f_transaction_id\"5\n" +
	"\x0eDeleteResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x03R\fdeletedCount\"\xbc\x01\n" +
	"\x11DeleteManyRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12,\n" +
	"\x06filter\x18\x03 \x01(\v2\x14.mongocore.v1.FilterR\x06filter\x12*\n" +
	"\x0etransaction_id\x18\x04 \x01(\tH\x00R\rtransactionId\x88\x01\x01B\x11\n" +
	"\x0f_transaction_id\"9\n" +
	"\x12DeleteManyResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x03R\fdeletedCount\"\xad\x02\n" +
	"\x14FindAndModifyRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12,\n" +
	"\x06filter\x18\x03 \x01(\v2\x14.mongocore.v1.FilterR\x06filter\x12.\n" +
	"\x06update\x18\x04 \x01(\v2\x16.mongocore.v1.DocumentR\x06update\x12<\n" +
	"\aoptions\x18\x05 \x01(\v2\".mongocore.v1.FindAndModifyOptionsR\aoptions\x12*\n" +
	"\x0etransaction_id\x18\x06 \x01(\tH\x00R\rtransactionId\x88\x01\x01B\x11\n" +
	"\x0f_transaction_id\"]\n" +
	"\x15FindAndModifyResponse\x127\n" +
	"\bdocument\x18\x01 \x01(\v2\x16.mongocore.v1.DocumentH\x00R\bdocument\x88\x01\x01B\v\n" +
	"\t_document\"\xc1\x01\n" +
	"\x10AggregateRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x122\n" +
	"\bpipeline\x18\x03 \x01(\v2\x16.mongocore.v1.PipelineR\bpipeline\x12*\n" +
	"\x0etransaction_id\x18\x04 \x01(\tH\x00R\rtransactionId\x88\x01\x01B\x11\n" +
	"\x0f_transaction_id\"\x85\x01\n" +
	"\x11AggregateResponse\x124\n" +
	"\tdocuments\x18\x01 \x03(\v2\x16.mongocore.v1.DocumentR\tdocuments\x12:\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1e.mongocore.v1.ResponseMetadataR\bmetadata\"5\n" +
	"\x17BeginTransactionRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\"A\n" +
	"\x18BeginTransactionResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"A\n" +
	"\x18CommitTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"\x1b\n" +
	"\x19CommitTransactionResponse\"@\n" +
	"\x17AbortTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"\x1a\n" +
	"\x18AbortTransactionResponse\"U\n" +
	"\x17CreateCollectionRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\"\x1a\n" +
	"\x18CreateCollectionResponse\"\xb2\x01\n" +
	"\x12CreateIndexRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12*\n" +
	"\x04keys\x18\x03 \x01(\v2\x16.mongocore.v1.DocumentR\x04keys\x124\n" +
	"\aoptions\x18\x04 \x01(\v2\x1a.mongocore.v1.IndexOptionsR\aoptions\"4\n" +
	"\x13CreateIndexResponse\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\"\x16\n" +
	"\x14ListDatabasesRequest\"5\n" +
	"\x15ListDatabasesResponse\x12\x1c\n" +
	"\tdatabases\x18\x01 \x03(\tR\tdatabases\"4\n" +
	"\x16ListCollectionsRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\";\n" +
	"\x17ListCollectionsResponse\x12 \n" +
	"\vcollections\x18\x01 \x03(\tR\vcollections\"\x92\x01\n" +
	"\fWatchRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12#\n" +
	"\n" +
	"collection\x18\x02 \x01(\tH\x00R\n" +
	"collection\x88\x01\x01\x122\n" +
	"\bpipeline\x18\x03 \x01(\v2\x16.mongocore.v1.PipelineR\bpipelineB\r\n" +
	"\v_collection\"\xe3\x03\n" +
	"\n" +
	"WatchEvent\x12M\n" +
	"\x0eoperation_type\x18\x01 \x01(\x0e2&.mongocore.v1.WatchEvent.OperationTypeR\roperationType\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x127\n" +
	"\bdocument\x18\x04 \x01(\v2\x16.mongocore.v1.DocumentH\x00R\bdocument\x88\x01\x01\x12J\n" +
	"\x12update_description\x18\x05 \x01(\v2\x16.mongocore.v1.DocumentH\x01R\x11updateDescription\x88\x01\x01\x12>\n" +
	"\fdocument_key\x18\x06 \x01(\v2\x16.mongocore.v1.DocumentH\x02R\vdocumentKey\x88\x01\x01\"P\n" +
	"\rOperationType\x12\n" +
	"\n" +
	"\x06INSERT\x10\x00\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x02\x12\v\n" +
	"\aREPLACE\x10\x03\x12\x0e\n" +
	"\n" +
	"INVALIDATE\x10\x04B\v\n" +
	"\t_documentB\x15\n" +
	"\x13_update_descriptionB\x0f\n" +
	"\r_document_key2\xda\v\n" +
	"\tMongoCore\x12=\n" +
	"\x04Find\x12\x19.mongocore.v1.FindRequest\x1a\x1a.mongocore.v1.FindResponse\x12F\n" +
	"\aFindOne\x12\x1c.mongocore.v1.FindOneRequest\x1a\x1d.mongocore.v1.FindOneResponse\x12C\n" +
	"\x06Insert\x12\x1b.mongocore.v1.InsertRequest\x1a\x1c.mongocore.v1.InsertResponse\x12O\n" +
	"\n" +
	"InsertMany\x12\x1f.mongocore.v1.InsertManyRequest\x1a .mongocore.v1.InsertManyResponse\x12C\n" +
	"\x06Update\x12\x1b.mongocore.v1.UpdateRequest\x1a\x1c.mongocore.v1.UpdateResponse\x12O\n" +
	"\n" +
	"UpdateMany\x12\x1f.mongocore.v1.UpdateManyRequest\x1a .mongocore.v1.UpdateManyResponse\x12C\n" +
	"\x06Delete\x12\x1b.mongocore.v1.DeleteRequest\x1a\x1c.mongocore.v1.DeleteResponse\x12O\n" +
	"\n" +
	"DeleteMany\x12\x1f.mongocore.v1.DeleteManyRequest\x1a .mongocore.v1.DeleteManyResponse\x12X\n" +
	"\rFindAndModify\x12\".mongocore.v1.FindAndModifyRequest\x1a#.mongocore.v1.FindAndModifyResponse\x12L\n" +
	"\tAggregate\x12\x1e.mongocore.v1.AggregateRequest\x1a\x1f.mongocore.v1.AggregateResponse\x12a\n" +
	"\x10BeginTransaction\x12%.mongocore.v1.BeginTransactionRequest\x1a&.mongocore.v1.BeginTransactionResponse\x12d\n" +
	"\x11CommitTransaction\x12&.mongocore.v1.CommitTransactionRequest\x1a'.mongocore.v1.CommitTransactionResponse\x12a\n" +
	"\x10AbortTransaction\x12%.mongocore.v1.AbortTransactionRequest\x1a&.mongocore.v1.AbortTransactionResponse\x12a\n" +
	"\x10CreateCollection\x12%.mongocore.v1.CreateCollectionRequest\x1a&.mongocore.v1.CreateCollectionResponse\x12R\n" +
	"\vCreateIndex\x12 .mongocore.v1.CreateIndexRequest\x1a!.mongocore.v1.CreateIndexResponse\x12X\n" +
	"\rListDatabases\x12\".mongocore.v1.ListDatabasesRequest\x1a#.mongocore.v1.ListDatabasesResponse\x12^\n" +
	"\x0fListCollections\x12$.mongocore.v1.ListCollectionsRequest\x1a%.mongocore.v1.ListCollectionsResponse\x12?\n" +
	"\x05Watch\x12\x1a.mongocore.v1.WatchRequest\x1a\x18.mongocore.v1.WatchEvent0\x01B-Z+github.com/rozza/mongocore/clients/go/protob\x06proto3"

var (
	file_mongocore_v1_mongocore_proto_rawDescOnce sync.Once
	file_mongocore_v1_mongocore_proto_rawDescData []byte
)

func file_mongocore_v1_mongocore_proto_rawDescGZIP() []byte {
	file_mongocore_v1_mongocore_proto_rawDescOnce.Do(func() {
		file_mongocore_v1_mongocore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mongocore_v1_mongocore_proto_rawDesc), len(file_mongocore_v1_mongocore_proto_rawDesc)))
	})
	return file_mongocore_v1_mongocore_proto_rawDescData
}

var file_mongocore_v1_mongocore_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mongocore_v1_mongocore_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_mongocore_v1_mongocore_proto_goTypes = []any{
	(WatchEvent_OperationType)(0),     // 0: mongocore.v1.WatchEvent.OperationType
	(*FindRequest)(nil),               // 1: mongocore.v1.FindRequest
	(*FindResponse)(nil),              // 2: mongocore.v1.FindResponse
	(*FindOneRequest)(nil),            // 3: mongocore.v1.FindOneRequest
	(*FindOneResponse)(nil),           // 4: mongocore.v1.FindOneResponse
	(*InsertRequest)(nil),             // 5: mongocore.v1.InsertRequest
	(*InsertResponse)(nil),            // 6: mongocore.v1.InsertResponse
	(*InsertManyRequest)(nil),         // 7: mongocore.v1.InsertManyRequest
	(*InsertManyResponse)(nil),        // 8: mongocore.v1.InsertManyResponse
	(*UpdateRequest)(nil),             // 9: mongocore.v1.UpdateRequest
	(*UpdateResponse)(nil),            // 10: mongocore.v1.UpdateResponse
	(*UpdateManyRequest)(nil),         // 11: mongocore.v1.UpdateManyRequest
	(*UpdateManyResponse)(nil),        // 12: mongocore.v1.UpdateManyResponse
	(*DeleteRequest)(nil),             // 13: mongocore.v1.DeleteRequest
	(*DeleteResponse)(nil),            // 14: mongocore.v1.DeleteResponse
	(*DeleteManyRequest)(nil),         // 15: mongocore.v1.DeleteManyRequest
	(*DeleteManyResponse)(nil),        // 16: mongocore.v1.DeleteManyResponse
	(*FindAndModifyRequest)(nil),      // 17: mongocore.v1.FindAndModifyRequest
	(*FindAndModifyResponse)(nil),     // 18: mongocore.v1.FindAndModifyResponse
	(*AggregateRequest)(nil),          // 19: mongocore.v1.AggregateRequest
	(*AggregateResponse)(nil),         // 20: mongocore.v1.AggregateResponse
	(*BeginTransactionRequest)(nil),   // 21: mongocore.v1.BeginTransactionRequest
	(*BeginTransactionResponse)(nil),  // 22: mongocore.v1.BeginTransactionResponse
	(*CommitTransactionRequest)(nil),  // 23: mongocore.v1.CommitTransactionRequest
	(*CommitTransactionResponse)(nil), // 24: mongocore.v1.CommitTransactionResponse
	(*AbortTransactionRequest)(nil),   // 25: mongocore.v1.AbortTransactionRequest
	(*AbortTransactionResponse)(nil),  // 26: mongocore.v1.AbortTransactionResponse
	(*CreateCollectionRequest)(nil),   // 27: mongocore.v1.CreateCollectionRequest
	(*CreateCollectionResponse)(nil),  // 28: mongocore.v1.CreateCollectionResponse
	(*CreateIndexRequest)(nil),        // 29: mongocore.v1.CreateIndexRequest
	(*CreateIndexResponse)(nil),       // 30: mongocore.v1.CreateIndexResponse
	(*ListDatabasesRequest)(nil),      // 31: mongocore.v1.ListDatabasesRequest
	(*ListDatabasesResponse)(nil),     // 32: mongocore.v1.ListDatabasesResponse
	(*ListCollectionsRequest)(nil),    // 33: mongocore.v1.ListCollectionsRequest
	(*ListCollectionsResponse)(nil),   // 34: mongocore.v1.ListCollectionsResponse
	(*WatchRequest)(nil),              // 35: mongocore.v1.WatchRequest
	(*WatchEvent)(nil),                // 36: mongocore.v1.WatchEvent
	(*Filter)(nil),                    // 37: mongocore.v1.Filter
	(*FindOptions)(nil),               // 38: mongocore.v1.FindOptions
	(*Document)(nil),                  // 39: mongocore.v1.Document
	(*ResponseMetadata)(nil),          // 40: mongocore.v1.ResponseMetadata
	(*FindAndModifyOptions)(nil),      // 41: mongocore.v1.FindAndModifyOptions
	(*Pipeline)(nil),                  // 42: mongocore.v1.Pipeline
	(*IndexOptions)(nil),              // 43: mongocore.v1.IndexOptions
}
var file_mongocore_v1_mongocore_proto_depIdxs = []int32{
	37, // 0: mongocore.v1.FindRequest.filter:type_name -> mongocore.v1.Filter
	38, // 1: mongocore.v1.FindRequest.options:type_name -> mongocore.v1.FindOptions
	39, // 2: mongocore.v1.FindResponse.documents:type_name -> mongocore.v1.Document
	40, // 3: mongocore.v1.FindResponse.metadata:type_name -> mongocore.v1.ResponseMetadata
	37, // 4: mongocore.v1.FindOneRequest.filter:type_name -> mongocore.v1.Filter
	38, // 5: mongocore.v1.FindOneRequest.options:type_name -> mongocore.v1.FindOptions
	39, // 6: mongocore.v1.FindOneResponse.document:type_name -> mongocore.v1.Document
	40, // 7: mongocore.v1.FindOneResponse.metadata:type_name -> mongocore.v1.ResponseMetadata
	39, // 8: mongocore.v1.InsertRequest.document:type_name -> mongocore.v1.Document
	39, // 9: mongocore.v1.InsertManyRequest.documents:type_name -> mongocore.v1.Document
	37, // 10: mongocore.v1.UpdateRequest.filter:type_name -> mongocore.v1.Filter
	39, // 11: mongocore.v1.UpdateRequest.update:type_name -> mongocore.v1.Document
	37, // 12: mongocore.v1.UpdateManyRequest.filter:type_name -> mongocore.v1.Filter
	39, // 13: mongocore.v1.UpdateManyRequest.update:type_name -> mongocore.v1.Document
	37, // 14: mongocore.v1.DeleteRequest.filter:type_name -> mongocore.v1.Filter
	37, // 15: mongocore.v1.DeleteManyRequest.filter:type_name -> mongocore.v1.Filter
	37, // 16: mongocore.v1.FindAndModifyRequest.filter:type_name -> mongocore.v1.Filter
	39, // 17: mongocore.v1.FindAndModifyRequest.update:type_name -> mongocore.v1.Document
	41, // 18: mongocore.v1.FindAndModifyRequest.options:type_name -> mongocore.v1.FindAndModifyOptions
	39, // 19: mongocore.v1.FindAndModifyResponse.document:type_name -> mongocore.v1.Document
	42, // 20: mongocore.v1.AggregateRequest.pipeline:type_name -> mongocore.v1.Pipeline
	39, // 21: mongocore.v1.AggregateResponse.documents:type_name -> mongocore.v1.Document
	40, // 22: mongocore.v1.AggregateResponse.metadata:type_name -> mongocore.v1.ResponseMetadata
	39, // 23: mongocore.v1.CreateIndexRequest.keys:type_name -> mongocore.v1.Document
	43, // 24: mongocore.v1.CreateIndexRequest.options:type_name -> mongocore.v1.IndexOptions
	42, // 25: mongocore.v1.WatchRequest.pipeline:type_name -> mongocore.v1.Pipeline
	0,  // 26: mongocore.v1.WatchEvent.operation_type:type_name -> mongocore.v1.WatchEvent.OperationType
	39, // 27: mongocore.v1.WatchEvent.document:type_name -> mongocore.v1.Document
	39, // 28: mongocore.v1.WatchEvent.update_description:type_name -> mongocore.v1.Document
	39, // 29: mongocore.v1.WatchEvent.document_key:type_name -> mongocore.v1.Document
	1,  // 30: mongocore.v1.MongoCore.Find:input_type -> mongocore.v1.FindRequest
	3,  // 31: mongocore.v1.MongoCore.FindOne:input_type -> mongocore.v1.FindOneRequest
	5,  // 32: mongocore.v1.MongoCore.Insert:input_type -> mongocore.v1.InsertRequest
	7,  // 33: mongocore.v1.MongoCore.InsertMany:input_type -> mongocore.v1.InsertManyRequest
	9,  // 34: mongocore.v1.MongoCore.Update:input_type -> mongocore.v1.UpdateRequest
	11, // 35: mongocore.v1.MongoCore.UpdateMany:input_type -> mongocore.v1.UpdateManyRequest
	13, // 36: mongocore.v1.MongoCore.Delete:input_type -> mongocore.v1.DeleteRequest
	15, // 37: mongocore.v1.MongoCore.DeleteMany:input_type -> mongocore.v1.DeleteManyRequest
	17, // 38: mongocore.v1.MongoCore.FindAndModify:input_type -> mongocore.v1.FindAndModifyRequest
	19, // 39: mongocore.v1.MongoCore.Aggregate:input_type -> mongocore.v1.AggregateRequest
	21, // 40: mongocore.v1.MongoCore.BeginTransaction:input_type -> mongocore.v1.BeginTransactionRequest
	23, // 41: mongocore.v1.MongoCore.CommitTransaction:input_type -> mongocore.v1.CommitTransactionRequest
	25, // 42: mongocore.v1.MongoCore.AbortTransaction:input_type -> mongocore.v1.AbortTransactionRequest
	27, // 43: mongocore.v1.MongoCore.CreateCollection:input_type -> mongocore.v1.CreateCollectionRequest
	29, // 44: mongocore.v1.MongoCore.CreateIndex:input_type -> mongocore.v1.CreateIndexRequest
	31, // 45: mongocore.v1.MongoCore.ListDatabases:input_type -> mongocore.v1.ListDatabasesRequest
	33, // 46: mongocore.v1.MongoCore.ListCollections:input_type -> mongocore.v1.ListCollectionsRequest
	35, // 47: mongocore.v1.MongoCore.Watch:input_type -> mongocore.v1.WatchRequest
	2,  // 48: mongocore.v1.MongoCore.Find:output_type -> mongocore.v1.FindResponse
	4,  // 49: mongocore.v1.MongoCore.FindOne:output_type -> mongocore.v1.FindOneResponse
	6,  // 50: mongocore.v1.MongoCore.Insert:output_type -> mongocore.v1.InsertResponse
	8,  // 51: mongocore.v1.MongoCore.InsertMany:output_type -> mongocore.v1.InsertManyResponse
	10, // 52: mongocore.v1.MongoCore.Update:output_type -> mongocore.v1.UpdateResponse
	12, // 53: mongocore.v1.MongoCore.UpdateMany:output_type -> mongocore.v1.UpdateManyResponse
	14, // 54: mongocore.v1.MongoCore.Delete:output_type -> mongocore.v1.DeleteResponse
	16, // 55: mongocore.v1.MongoCore.DeleteMany:output_type -> mongocore.v1.DeleteManyResponse
	18, // 56: mongocore.v1.MongoCore.FindAndModify:output_type -> mongocore.v1.FindAndModifyResponse
	20, // 57: mongocore.v1.MongoCore.Aggregate:output_type -> mongocore.v1.AggregateResponse
	22, // 58: mongocore.v1.MongoCore.BeginTransaction:output_type -> mongocore.v1.BeginTransactionResponse
	24, // 59: mongocore.v1.MongoCore.CommitTransaction:output_type -> mongocore.v1.CommitTransactionResponse
	26, // 60: mongocore.v1.MongoCore.AbortTransaction:output_type -> mongocore.v1.AbortTransactionResponse
	28, // 61: mongocore.v1.MongoCore.CreateCollection:output_type -> mongocore.v1.CreateCollectionResponse
	30, // 62: mongocore.v1.MongoCore.CreateIndex:output_type -> mongocore.v1.CreateIndexResponse
	32, // 63: mongocore.v1.MongoCore.ListDatabases:output_type -> mongocore.v1.ListDatabasesResponse
	34, // 64: mongocore.v1.MongoCore.ListCollections:output_type -> mongocore.v1.ListCollectionsResponse
	36, // 65: mongocore.v1.MongoCore.Watch:output_type -> mongocore.v1.WatchEvent
	48, // [48:66] is the sub-list for method output_type
	30, // [30:48] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_mongocore_v1_mongocore_proto_init() }
func file_mongocore_v1_mongocore_proto_init() {
	if File_mongocore_v1_mongocore_proto != nil {
		return
	}
	file_mongocore_v1_types_proto_init()
	file_mongocore_v1_mongocore_proto_msgTypes[0].OneofWrappers = []any{}
	file_mongocore_v1_mongocore_proto_msgTypes[2].OneofWrappers = []any{}
	file_mongocore_v1_mongocore_proto_msgTypes[3].OneofWrappers = []any{}
	file_mongocore_v1_mongocore_proto_msgTypes[4].OneofWrappers = []any{}
	file_mongocore_v1_mongocore_proto_msgTypes[6].OneofWrappers = []any{}
	file_mongocore_v1_mongocore_proto_msgTypes[8].OneofWrappers = []any{}
	file_mongocore_v1_mongocore_proto_msgTypes[9].OneofWrappers = []any{}
	file_mongocore_v1_mongocore_proto_msgTypes[10].OneofWrappers = []any{}
	file_mongocore_v1_mongocore_proto_msgTypes[11].OneofWrappers = []any{}
	file_mongocore_v1_mongocore_proto_msgTypes[12].OneofWrappers = []any{}
	file_mongocore_v1_mongocore_proto_msgTypes[14].OneofWrappers = []any{}
	file_mongocore_v1_mongocore_proto_msgTypes[16].OneofWrappers = []any{}
	file_mongocore_v1_mongocore_proto_msgTypes[17].OneofWrappers = []any{}
	file_mongocore_v1_mongocore_proto_msgTypes[18].OneofWrappers = []any{}
	file_mongocore_v1_mongocore_proto_msgTypes[34].OneofWrappers = []any{}
	file_mongocore_v1_mongocore_proto_msgTypes[35].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mongocore_v1_mongocore_proto_rawDesc), len(file_mongocore_v1_mongocore_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mongocore_v1_mongocore_proto_goTypes,
		DependencyIndexes: file_mongocore_v1_mongocore_proto_depIdxs,
		EnumInfos:         file_mongocore_v1_mongocore_proto_enumTypes,
		MessageInfos:      file_mongocore_v1_mongocore_proto_msgTypes,
	}.Build()
	File_mongocore_v1_mongocore_proto = out.File
	file_mongocore_v1_mongocore_proto_goTypes = nil
	file_mongocore_v1_mongocore_proto_depIdxs = nil
}
