// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: mongocore/v1/types.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAndModifyOptions_ReturnDocument int32

const (
	FindAndModifyOptions_BEFORE FindAndModifyOptions_ReturnDocument = 0
	FindAndModifyOptions_AFTER  FindAndModifyOptions_ReturnDocument = 1
)

// Enum value maps for FindAndModifyOptions_ReturnDocument.
var (
	FindAndModifyOptions_ReturnDocument_name = map[int32]string{
		0: "BEFORE",
		1: "AFTER",
	}
	FindAndModifyOptions_ReturnDocument_value = map[string]int32{
		"BEFORE": 0,
		"AFTER":  1,
	}
)

func (x FindAndModifyOptions_ReturnDocument) Enum() *FindAndModifyOptions_ReturnDocument {
	p := new(FindAndModifyOptions_ReturnDocument)
	*p = x
	return p
}

func (x FindAndModifyOptions_ReturnDocument) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FindAndModifyOptions_ReturnDocument) Descriptor() protoreflect.EnumDescriptor {
	return file_mongocore_v1_types_proto_enumTypes[0].Descriptor()
}

func (FindAndModifyOptions_ReturnDocument) Type() protoreflect.EnumType {
	return &file_mongocore_v1_types_proto_enumTypes[0]
}

func (x FindAndModifyOptions_ReturnDocument) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FindAndModifyOptions_ReturnDocument.Descriptor instead.
func (FindAndModifyOptions_ReturnDocument) EnumDescriptor() ([]byte, []int) {
	return file_mongocore_v1_types_proto_rawDescGZIP(), []int{5, 0}
}

// A BSON document represented as raw bytes (avoids double-serialization)
type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_mongocore_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // BSON filter document
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_mongocore_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *Filter) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Pipeline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stages        [][]byte               `protobuf:"bytes,1,rep,name=stages,proto3" json:"stages,omitempty"` // Each stage is a BSON document
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pipeline) Reset() {
	*x = Pipeline{}
	mi := &file_mongocore_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pipeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pipeline) ProtoMessage() {}

func (x *Pipeline) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pipeline.ProtoReflect.Descriptor instead.
func (*Pipeline) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *Pipeline) GetStages() [][]byte {
	if x != nil {
		return x.Stages
	}
	return nil
}

type FindOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         *int64                 `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Skip          *int64                 `protobuf:"varint,2,opt,name=skip,proto3,oneof" json:"skip,omitempty"`
	Sort          []byte                 `protobuf:"bytes,3,opt,name=sort,proto3,oneof" json:"sort,omitempty"`             // BSON document
	Projection    []byte                 `protobuf:"bytes,4,opt,name=projection,proto3,oneof" json:"projection,omitempty"` // BSON document
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindOptions) Reset() {
	*x = FindOptions{}
	mi := &file_mongocore_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOptions) ProtoMessage() {}

func (x *FindOptions) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOptions.ProtoReflect.Descriptor instead.
func (*FindOptions) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *FindOptions) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *FindOptions) GetSkip() int64 {
	if x != nil && x.Skip != nil {
		return *x.Skip
	}
	return 0
}

func (x *FindOptions) GetSort() []byte {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *FindOptions) GetProjection() []byte {
	if x != nil {
		return x.Projection
	}
	return nil
}

type IndexOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Unique        *bool                  `protobuf:"varint,2,opt,name=unique,proto3,oneof" json:"unique,omitempty"`
	Sparse        *bool                  `protobuf:"varint,3,opt,name=sparse,proto3,oneof" json:"sparse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexOptions) Reset() {
	*x = IndexOptions{}
	mi := &file_mongocore_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexOptions) ProtoMessage() {}

func (x *IndexOptions) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexOptions.ProtoReflect.Descriptor instead.
func (*IndexOptions) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *IndexOptions) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *IndexOptions) GetUnique() bool {
	if x != nil && x.Unique != nil {
		return *x.Unique
	}
	return false
}

func (x *IndexOptions) GetSparse() bool {
	if x != nil && x.Sparse != nil {
		return *x.Sparse
	}
	return false
}

type FindAndModifyOptions struct {
	state          protoimpl.MessageState              `protogen:"open.v1"`
	ReturnDocument FindAndModifyOptions_ReturnDocument `protobuf:"varint,1,opt,name=return_document,json=returnDocument,proto3,enum=mongocore.v1.FindAndModifyOptions_ReturnDocument" json:"return_document,omitempty"`
	Upsert         bool                                `protobuf:"varint,2,opt,name=upsert,proto3" json:"upsert,omitempty"`
	Sort           []byte                              `protobuf:"bytes,3,opt,name=sort,proto3,oneof" json:"sort,omitempty"` // BSON document
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FindAndModifyOptions) Reset() {
	*x = FindAndModifyOptions{}
	mi := &file_mongocore_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAndModifyOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAndModifyOptions) ProtoMessage() {}

func (x *FindAndModifyOptions) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAndModifyOptions.ProtoReflect.Descriptor instead.
func (*FindAndModifyOptions) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *FindAndModifyOptions) GetReturnDocument() FindAndModifyOptions_ReturnDocument {
	if x != nil {
		return x.ReturnDocument
	}
	return FindAndModifyOptions_BEFORE
}

func (x *FindAndModifyOptions) GetUpsert() bool {
	if x != nil {
		return x.Upsert
	}
	return false
}

func (x *FindAndModifyOptions) GetSort() []byte {
	if x != nil {
		return x.Sort
	}
	return nil
}

// Common metadata in responses
type ResponseMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchMethod  string                 `protobuf:"bytes,1,opt,name=search_method,json=searchMethod,proto3" json:"search_method,omitempty"` // "vector", "fulltext", "compiled_query", ""
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseMetadata) Reset() {
	*x = ResponseMetadata{}
	mi := &file_mongocore_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMetadata) ProtoMessage() {}

func (x *ResponseMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMetadata.ProtoReflect.Descriptor instead.
func (*ResponseMetadata) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *ResponseMetadata) GetSearchMethod() string {
	if x != nil {
		return x.SearchMethod
	}
	return ""
}

var File_mongocore_v1_types_proto protoreflect.FileDescriptor

const file_mongocore_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x18mongocore/v1/types.proto\x12\fmongocore.v1\"\x1e\n" +
	"\bDocument\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x1c\n" +
	"\x06Filter\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\"\n" +
	"\bPipeline\x12\x16\n" +
	"\x06stages\x18\x01 \x03(\fR\x06stages\"\xaa\x01\n" +
	"\vFindOptions\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\x03H\x00R\x05limit\x88\x01\x01\x12\x17\n" +
	"\x04skip\x18\x02 \x01(\x03H\x01R\x04skip\x88\x01\x01\x12\x17\n" +
	"\x04sort\x18\x03 \x01(\fH\x02R\x04sort\x88\x01\x01\x12#\n" +
	"\n" +
	"projection\x18\x04 \x01(\fH\x03R\n" +
	"projection\x88\x01\x01B\b\n" +
	"\x06_limitB\a\n" +
	"\x05_skipB\a\n" +
	"\x05_sortB\r\n" +
	"\v_projection\"\x80\x01\n" +
	"\fIndexOptions\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1b\n" +
	"\x06unique\x18\x02 \x01(\bH\x01R\x06unique\x88\x01\x01\x12\x1b\n" +
	"\x06sparse\x18\x03 \x01(\bH\x02R\x06sparse\x88\x01\x01B\a\n" +
	"\x05_nameB\t\n" +
	"\a_uniqueB\t\n" +
	"\a_sparse\"\xd5\x01\n" +
	"\x14FindAndModifyOptions\x12Z\n" +
	"\x0freturn_document\x18\x01 \x01(\x0e21.mongocore.v1.FindAndModifyOptions.ReturnDocumentR\x0ereturnDocument\x12\x16\n" +
	"\x06upsert\x18\x02 \x01(\bR\x06upsert\x12\x17\n" +
	"\x04sort\x18\x03 \x01(\fH\x00R\x04sort\x88\x01\x01\"'\n" +
	"\x0eReturnDocument\x12\n" +
	"\n" +
	"\x06BEFORE\x10\x00\x12\t\n" +
	"\x05AFTER\x10\x01B\a\n" +
	"\x05_sort\"7\n" +
	"\x10ResponseMetadata\x12#\n" +
	"\rsearch_method\x18\x01 \x01(\tR\fsearchMethodB-Z+github.com/rozza/mongocore/clients/go/protob\x06proto3"

var (
	file_mongocore_v1_types_proto_rawDescOnce sync.Once
	file_mongocore_v1_types_proto_rawDescData []byte
)

func file_mongocore_v1_types_proto_rawDescGZIP() []byte {
	file_mongocore_v1_types_proto_rawDescOnce.Do(func() {
		file_mongocore_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mongocore_v1_types_proto_rawDesc), len(file_mongocore_v1_types_proto_rawDesc)))
	})
	return file_mongocore_v1_types_proto_rawDescData
}

var file_mongocore_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mongocore_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_mongocore_v1_types_proto_goTypes = []any{
	(FindAndModifyOptions_ReturnDocument)(0), // 0: mongocore.v1.FindAndModifyOptions.ReturnDocument
	(*Document)(nil),                         // 1: mongocore.v1.Document
	(*Filter)(nil),                           // 2: mongocore.v1.Filter
	(*Pipeline)(nil),                         // 3: mongocore.v1.Pipeline
	(*FindOptions)(nil),                      // 4: mongocore.v1.FindOptions
	(*IndexOptions)(nil),                     // 5: mongocore.v1.IndexOptions
	(*FindAndModifyOptions)(nil),             // 6: mongocore.v1.FindAndModifyOptions
	(*ResponseMetadata)(nil),                 // 7: mongocore.v1.ResponseMetadata
}
var file_mongocore_v1_types_proto_depIdxs = []int32{
	0, // 0: mongocore.v1.FindAndModifyOptions.return_document:type_name -> mongocore.v1.FindAndModifyOptions.ReturnDocument
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mongocore_v1_types_proto_init() }
func file_mongocore_v1_types_proto_init() {
	if File_mongocore_v1_types_proto != nil {
		return
	}
	file_mongocore_v1_types_proto_msgTypes[3].OneofWrappers = []any{}
	file_mongocore_v1_types_proto_msgTypes[4].OneofWrappers = []any{}
	file_mongocore_v1_types_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mongocore_v1_types_proto_rawDesc), len(file_mongocore_v1_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mongocore_v1_types_proto_goTypes,
		DependencyIndexes: file_mongocore_v1_types_proto_depIdxs,
		EnumInfos:         file_mongocore_v1_types_proto_enumTypes,
		MessageInfos:      file_mongocore_v1_types_proto_msgTypes,
	}.Build()
	File_mongocore_v1_types_proto = out.File
	file_mongocore_v1_types_proto_goTypes = nil
	file_mongocore_v1_types_proto_depIdxs = nil
}
