// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: mongocore/v1/types.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAndModifyOptions_ReturnDocument int32

const (
	FindAndModifyOptions_BEFORE FindAndModifyOptions_ReturnDocument = 0
	FindAndModifyOptions_AFTER  FindAndModifyOptions_ReturnDocument = 1
)

// Enum value maps for FindAndModifyOptions_ReturnDocument.
var (
	FindAndModifyOptions_ReturnDocument_name = map[int32]string{
		0: "BEFORE",
		1: "AFTER",
	}
	FindAndModifyOptions_ReturnDocument_value = map[string]int32{
		"BEFORE": 0,
		"AFTER":  1,
	}
)

func (x FindAndModifyOptions_ReturnDocument) Enum() *FindAndModifyOptions_ReturnDocument {
	p := new(FindAndModifyOptions_ReturnDocument)
	*p = x
	return p
}

func (x FindAndModifyOptions_ReturnDocument) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FindAndModifyOptions_ReturnDocument) Descriptor() protoreflect.EnumDescriptor {
	return file_mongocore_v1_types_proto_enumTypes[0].Descriptor()
}

func (FindAndModifyOptions_ReturnDocument) Type() protoreflect.EnumType {
	return &file_mongocore_v1_types_proto_enumTypes[0]
}

func (x FindAndModifyOptions_ReturnDocument) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FindAndModifyOptions_ReturnDocument.Descriptor instead.
func (FindAndModifyOptions_ReturnDocument) EnumDescriptor() ([]byte, []int) {
	return file_mongocore_v1_types_proto_rawDescGZIP(), []int{5, 0}
}

// A BSON document represented as raw bytes (avoids double-serialization)
type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_mongocore_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // BSON filter document
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_mongocore_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *Filter) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Pipeline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stages        [][]byte               `protobuf:"bytes,1,rep,name=stages,proto3" json:"stages,omitempty"` // Each stage is a BSON document
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pipeline) Reset() {
	*x = Pipeline{}
	mi := &file_mongocore_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pipeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pipeline) ProtoMessage() {}

func (x *Pipeline) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pipeline.ProtoReflect.Descriptor instead.
func (*Pipeline) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *Pipeline) GetStages() [][]byte {
	if x != nil {
		return x.Stages
	}
	return nil
}

type FindOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         *int64                 `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Skip          *int64                 `protobuf:"varint,2,opt,name=skip,proto3,oneof" json:"skip,omitempty"`
	Sort          []byte                 `protobuf:"bytes,3,opt,name=sort,proto3,oneof" json:"sort,omitempty"`             // BSON document
	Projection    []byte                 `protobuf:"bytes,4,opt,name=projection,proto3,oneof" json:"projection,omitempty"` // BSON document
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindOptions) Reset() {
	*x = FindOptions{}
	mi := &file_mongocore_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOptions) ProtoMessage() {}

func (x *FindOptions) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOptions.ProtoReflect.Descriptor instead.
func (*FindOptions) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *FindOptions) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *FindOptions) GetSkip() int64 {
	if x != nil && x.Skip != nil {
		return *x.Skip
	}
	return 0
}

func (x *FindOptions) GetSort() []byte {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *FindOptions) GetProjection() []byte {
	if x != nil {
		return x.Projection
	}
	return nil
}

type IndexOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Unique        *bool                  `protobuf:"varint,2,opt,name=unique,proto3,oneof" json:"unique,omitempty"`
	Sparse        *bool                  `protobuf:"varint,3,opt,name=sparse,proto3,oneof" json:"sparse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexOptions) Reset() {
	*x = IndexOptions{}
	mi := &file_mongocore_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexOptions) ProtoMessage() {}

func (x *IndexOptions) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexOptions.ProtoReflect.Descriptor instead.
func (*IndexOptions) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *IndexOptions) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *IndexOptions) GetUnique() bool {
	if x != nil && x.Unique != nil {
		return *x.Unique
	}
	return false
}

func (x *IndexOptions) GetSparse() bool {
	if x != nil && x.Sparse != nil {
		return *x.Sparse
	}
	return false
}

type FindAndModifyOptions struct {
	state          protoimpl.MessageState              `protogen:"open.v1"`
	ReturnDocument FindAndModifyOptions_ReturnDocument `protobuf:"varint,1,opt,name=return_document,json=returnDocument,proto3,enum=mongocore.v1.FindAndModifyOptions_ReturnDocument" json:"return_document,omitempty"`
	Upsert         bool                                `protobuf:"varint,2,opt,name=upsert,proto3" json:"upsert,omitempty"`
	Sort           []byte                              `protobuf:"bytes,3,opt,name=sort,proto3,oneof" json:"sort,omitempty"` // BSON document
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FindAndModifyOptions) Reset() {
	*x = FindAndModifyOptions{}
	mi := &file_mongocore_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAndModifyOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAndModifyOptions) ProtoMessage() {}

func (x *FindAndModifyOptions) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAndModifyOptions.ProtoReflect.Descriptor instead.
func (*FindAndModifyOptions) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *FindAndModifyOptions) GetReturnDocument() FindAndModifyOptions_ReturnDocument {
	if x != nil {
		return x.ReturnDocument
	}
	return FindAndModifyOptions_BEFORE
}

func (x *FindAndModifyOptions) GetUpsert() bool {
	if x != nil {
		return x.Upsert
	}
	return false
}

func (x *FindAndModifyOptions) GetSort() []byte {
	if x != nil {
		return x.Sort
	}
	return nil
}

// Common metadata in responses
type ResponseMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchMethod  string                 `protobuf:"bytes,1,opt,name=search_method,json=searchMethod,proto3" json:"search_method,omitempty"` // "vector", "fulltext", "compiled_query", ""
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseMetadata) Reset() {
	*x = ResponseMetadata{}
	mi := &file_mongocore_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMetadata) ProtoMessage() {}

func (x *ResponseMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMetadata.ProtoReflect.Descriptor instead.
func (*ResponseMetadata) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *ResponseMetadata) GetSearchMethod() string {
	if x != nil {
		return x.SearchMethod
	}
	return ""
}

// Streaming batch of documents (used by FindStream, AggregateStream)
type DocumentBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*Document            `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	BatchIndex    uint32                 `protobuf:"varint,2,opt,name=batch_index,json=batchIndex,proto3" json:"batch_index,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentBatch) Reset() {
	*x = DocumentBatch{}
	mi := &file_mongocore_v1_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentBatch) ProtoMessage() {}

func (x *DocumentBatch) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentBatch.ProtoReflect.Descriptor instead.
func (*DocumentBatch) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_types_proto_rawDescGZIP(), []int{7}
}

func (x *DocumentBatch) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *DocumentBatch) GetBatchIndex() uint32 {
	if x != nil {
		return x.BatchIndex
	}
	return 0
}

func (x *DocumentBatch) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// Streaming insert batch (client-to-server)
type InsertBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Documents     []*Document            `protobuf:"bytes,3,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertBatch) Reset() {
	*x = InsertBatch{}
	mi := &file_mongocore_v1_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertBatch) ProtoMessage() {}

func (x *InsertBatch) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertBatch.ProtoReflect.Descriptor instead.
func (*InsertBatch) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_types_proto_rawDescGZIP(), []int{8}
}

func (x *InsertBatch) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *InsertBatch) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *InsertBatch) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

// Per-batch acknowledgment for bidirectional insert
type InsertBatchAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchIndex    uint32                 `protobuf:"varint,1,opt,name=batch_index,json=batchIndex,proto3" json:"batch_index,omitempty"`
	InsertedCount uint32                 `protobuf:"varint,2,opt,name=inserted_count,json=insertedCount,proto3" json:"inserted_count,omitempty"`
	Errors        []*InsertError         `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertBatchAck) Reset() {
	*x = InsertBatchAck{}
	mi := &file_mongocore_v1_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertBatchAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertBatchAck) ProtoMessage() {}

func (x *InsertBatchAck) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertBatchAck.ProtoReflect.Descriptor instead.
func (*InsertBatchAck) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_types_proto_rawDescGZIP(), []int{9}
}

func (x *InsertBatchAck) GetBatchIndex() uint32 {
	if x != nil {
		return x.BatchIndex
	}
	return 0
}

func (x *InsertBatchAck) GetInsertedCount() uint32 {
	if x != nil {
		return x.InsertedCount
	}
	return 0
}

func (x *InsertBatchAck) GetErrors() []*InsertError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type InsertError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertError) Reset() {
	*x = InsertError{}
	mi := &file_mongocore_v1_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertError) ProtoMessage() {}

func (x *InsertError) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertError.ProtoReflect.Descriptor instead.
func (*InsertError) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_types_proto_rawDescGZIP(), []int{10}
}

func (x *InsertError) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *InsertError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InsertError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// Response for unidirectional streaming insert
type InsertManyStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalInserted uint64                 `protobuf:"varint,1,opt,name=total_inserted,json=totalInserted,proto3" json:"total_inserted,omitempty"`
	Errors        []*InsertError         `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertManyStreamResponse) Reset() {
	*x = InsertManyStreamResponse{}
	mi := &file_mongocore_v1_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertManyStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertManyStreamResponse) ProtoMessage() {}

func (x *InsertManyStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mongocore_v1_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertManyStreamResponse.ProtoReflect.Descriptor instead.
func (*InsertManyStreamResponse) Descriptor() ([]byte, []int) {
	return file_mongocore_v1_types_proto_rawDescGZIP(), []int{11}
}

func (x *InsertManyStreamResponse) GetTotalInserted() uint64 {
	if x != nil {
		return x.TotalInserted
	}
	return 0
}

func (x *InsertManyStreamResponse) GetErrors() []*InsertError {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_mongocore_v1_types_proto protoreflect.FileDescriptor

const file_mongocore_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x18mongocore/v1/types.proto\x12\fmongocore.v1\"\x1e\n" +
	"\bDocument\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x1c\n" +
	"\x06Filter\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\"\n" +
	"\bPipeline\x12\x16\n" +
	"\x06stages\x18\x01 \x03(\fR\x06stages\"\xaa\x01\n" +
	"\vFindOptions\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\x03H\x00R\x05limit\x88\x01\x01\x12\x17\n" +
	"\x04skip\x18\x02 \x01(\x03H\x01R\x04skip\x88\x01\x01\x12\x17\n" +
	"\x04sort\x18\x03 \x01(\fH\x02R\x04sort\x88\x01\x01\x12#\n" +
	"\n" +
	"projection\x18\x04 \x01(\fH\x03R\n" +
	"projection\x88\x01\x01B\b\n" +
	"\x06_limitB\a\n" +
	"\x05_skipB\a\n" +
	"\x05_sortB\r\n" +
	"\v_projection\"\x80\x01\n" +
	"\fIndexOptions\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1b\n" +
	"\x06unique\x18\x02 \x01(\bH\x01R\x06unique\x88\x01\x01\x12\x1b\n" +
	"\x06sparse\x18\x03 \x01(\bH\x02R\x06sparse\x88\x01\x01B\a\n" +
	"\x05_nameB\t\n" +
	"\a_uniqueB\t\n" +
	"\a_sparse\"\xd5\x01\n" +
	"\x14FindAndModifyOptions\x12Z\n" +
	"\x0freturn_document\x18\x01 \x01(\x0e21.mongocore.v1.FindAndModifyOptions.ReturnDocumentR\x0ereturnDocument\x12\x16\n" +
	"\x06upsert\x18\x02 \x01(\bR\x06upsert\x12\x17\n" +
	"\x04sort\x18\x03 \x01(\fH\x00R\x04sort\x88\x01\x01\"'\n" +
	"\x0eReturnDocument\x12\n" +
	"\n" +
	"\x06BEFORE\x10\x00\x12\t\n" +
	"\x05AFTER\x10\x01B\a\n" +
	"\x05_sort\"7\n" +
	"\x10ResponseMetadata\x12#\n" +
	"\rsearch_method\x18\x01 \x01(\tR\fsearchMethod\"\x81\x01\n" +
	"\rDocumentBatch\x124\n" +
	"\tdocuments\x18\x01 \x03(\v2\x16.mongocore.v1.DocumentR\tdocuments\x12\x1f\n" +
	"\vbatch_index\x18\x02 \x01(\rR\n" +
	"batchIndex\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"\x7f\n" +
	"\vInsertBatch\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x124\n" +
	"\tdocuments\x18\x03 \x03(\v2\x16.mongocore.v1.DocumentR\tdocuments\"\x8b\x01\n" +
	"\x0eInsertBatchAck\x12\x1f\n" +
	"\vbatch_index\x18\x01 \x01(\rR\n" +
	"batchIndex\x12%\n" +
	"\x0einserted_count\x18\x02 \x01(\rR\rinsertedCount\x121\n" +
	"\x06errors\x18\x03 \x03(\v2\x19.mongocore.v1.InsertErrorR\x06errors\"Q\n" +
	"\vInsertError\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\"t\n" +
	"\x18InsertManyStreamResponse\x12%\n" +
	"\x0etotal_inserted\x18\x01 \x01(\x04R\rtotalInserted\x121\n" +
	"\x06errors\x18\x02 \x03(\v2\x19.mongocore.v1.InsertErrorR\x06errorsB-Z+github.com/rozza/mongocore/clients/go/protob\x06proto3"

var (
	file_mongocore_v1_types_proto_rawDescOnce sync.Once
	file_mongocore_v1_types_proto_rawDescData []byte
)

func file_mongocore_v1_types_proto_rawDescGZIP() []byte {
	file_mongocore_v1_types_proto_rawDescOnce.Do(func() {
		file_mongocore_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mongocore_v1_types_proto_rawDesc), len(file_mongocore_v1_types_proto_rawDesc)))
	})
	return file_mongocore_v1_types_proto_rawDescData
}

var file_mongocore_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mongocore_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_mongocore_v1_types_proto_goTypes = []any{
	(FindAndModifyOptions_ReturnDocument)(0), // 0: mongocore.v1.FindAndModifyOptions.ReturnDocument
	(*Document)(nil),                         // 1: mongocore.v1.Document
	(*Filter)(nil),                           // 2: mongocore.v1.Filter
	(*Pipeline)(nil),                         // 3: mongocore.v1.Pipeline
	(*FindOptions)(nil),                      // 4: mongocore.v1.FindOptions
	(*IndexOptions)(nil),                     // 5: mongocore.v1.IndexOptions
	(*FindAndModifyOptions)(nil),             // 6: mongocore.v1.FindAndModifyOptions
	(*ResponseMetadata)(nil),                 // 7: mongocore.v1.ResponseMetadata
	(*DocumentBatch)(nil),                    // 8: mongocore.v1.DocumentBatch
	(*InsertBatch)(nil),                      // 9: mongocore.v1.InsertBatch
	(*InsertBatchAck)(nil),                   // 10: mongocore.v1.InsertBatchAck
	(*InsertError)(nil),                      // 11: mongocore.v1.InsertError
	(*InsertManyStreamResponse)(nil),         // 12: mongocore.v1.InsertManyStreamResponse
}
var file_mongocore_v1_types_proto_depIdxs = []int32{
	0,  // 0: mongocore.v1.FindAndModifyOptions.return_document:type_name -> mongocore.v1.FindAndModifyOptions.ReturnDocument
	1,  // 1: mongocore.v1.DocumentBatch.documents:type_name -> mongocore.v1.Document
	1,  // 2: mongocore.v1.InsertBatch.documents:type_name -> mongocore.v1.Document
	11, // 3: mongocore.v1.InsertBatchAck.errors:type_name -> mongocore.v1.InsertError
	11, // 4: mongocore.v1.InsertManyStreamResponse.errors:type_name -> mongocore.v1.InsertError
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_mongocore_v1_types_proto_init() }
func file_mongocore_v1_types_proto_init() {
	if File_mongocore_v1_types_proto != nil {
		return
	}
	file_mongocore_v1_types_proto_msgTypes[3].OneofWrappers = []any{}
	file_mongocore_v1_types_proto_msgTypes[4].OneofWrappers = []any{}
	file_mongocore_v1_types_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mongocore_v1_types_proto_rawDesc), len(file_mongocore_v1_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mongocore_v1_types_proto_goTypes,
		DependencyIndexes: file_mongocore_v1_types_proto_depIdxs,
		EnumInfos:         file_mongocore_v1_types_proto_enumTypes,
		MessageInfos:      file_mongocore_v1_types_proto_msgTypes,
	}.Build()
	File_mongocore_v1_types_proto = out.File
	file_mongocore_v1_types_proto_goTypes = nil
	file_mongocore_v1_types_proto_depIdxs = nil
}
